import type {
  DashboardKPI,
  TrendDataPoint,
  ActivityEvent,
  LocationNode,
  TicketAnalytics,
  AuditAnalytics,
  CAPAAnalytics,
  TaskAnalytics,
  CustomDashboard,
  ExportConfig,
  CrossModuleSummary,
} from "./types";

// ====================================================================
// Helper: generate sparkline data
// ====================================================================

function generateSparkline(
  base: number,
  variance: number,
  count: number,
  trend: "up" | "down" | "flat" = "flat"
): Array<{ name: string; value: number }> {
  const points: Array<{ name: string; value: number }> = [];
  for (let i = 0; i < count; i++) {
    const trendAdj =
      trend === "up" ? (i / count) * variance * 2 : trend === "down" ? -(i / count) * variance * 2 : 0;
    const value = Math.max(0, Math.round(base + (Math.random() - 0.5) * variance + trendAdj));
    points.push({ name: `D${i + 1}`, value });
  }
  return points;
}

// ====================================================================
// 1. Dashboard KPIs (6 cards)
// ====================================================================

export const dashboardKPIs: DashboardKPI[] = [
  {
    id: "kpi_tickets_open",
    title: "Open Tickets",
    value: 23,
    unit: "tickets",
    trend: 8,
    trendLabel: "vs last 30 days",
    isPositive: false,
    sparklineData: generateSparkline(20, 8, 30, "up"),
    color: "#58A6FF",
    module: "tickets",
    linkTo: "/analytics/tickets",
  },
  {
    id: "kpi_compliance",
    title: "Compliance Score",
    value: 87,
    unit: "%",
    trend: -2,
    trendLabel: "vs last 30 days",
    isPositive: true,
    sparklineData: generateSparkline(85, 5, 30, "flat"),
    color: "#3FB950",
    module: "audits",
    linkTo: "/analytics/audits",
  },
  {
    id: "kpi_capa_overdue",
    title: "CAPA Overdue",
    value: 4,
    unit: "items",
    trend: 1,
    trendLabel: "vs last 30 days",
    isPositive: false,
    sparklineData: generateSparkline(3, 2, 30, "up"),
    color: "#F85149",
    module: "capa",
    linkTo: "/analytics/capa",
  },
  {
    id: "kpi_tasks_due",
    title: "Tasks Due",
    value: 12,
    unit: "tasks",
    trend: -3,
    trendLabel: "vs last 30 days",
    isPositive: false,
    sparklineData: generateSparkline(14, 4, 30, "down"),
    color: "#D29922",
    module: "tasks",
    linkTo: "/analytics/tasks",
  },
  {
    id: "kpi_sla",
    title: "SLA Compliance",
    value: 94,
    unit: "%",
    trend: 5,
    trendLabel: "vs last 30 days",
    isPositive: true,
    sparklineData: generateSparkline(92, 3, 30, "up"),
    color: "#388BFD",
    module: "sla",
    linkTo: "/analytics/tickets",
  },
  {
    id: "kpi_csat",
    title: "CSAT Score",
    value: "4.2",
    unit: "/5",
    trend: 2,
    trendLabel: "vs last 30 days",
    isPositive: true,
    sparklineData: generateSparkline(42, 3, 30, "up"),
    color: "#BC8CFF",
    module: "overall",
    linkTo: "/analytics/tickets",
  },
];

// ====================================================================
// 2. Trend Data Points (90 days)
// ====================================================================

function generateTrendData(): TrendDataPoint[] {
  const data: TrendDataPoint[] = [];
  const startDate = new Date("2025-12-15");

  for (let i = 0; i < 90; i++) {
    const d = new Date(startDate);
    d.setDate(d.getDate() + i);
    const dateStr = d.toISOString().split("T")[0];
    const month = `${String(d.getMonth() + 1).padStart(2, "0")}/${String(d.getDate()).padStart(2, "0")}`;

    data.push({
      date: month,
      compliance: Math.round(82 + Math.random() * 12 + (i / 90) * 3),
      csat: Math.round(75 + Math.random() * 15 + (i / 90) * 2),
      ticket_volume: Math.round(5 + Math.random() * 10),
      resolution_hours: +(3 + Math.random() * 4).toFixed(1),
      sla_compliance: Math.round(88 + Math.random() * 10),
      audit_score: Math.round(78 + Math.random() * 15),
    });
  }
  return data;
}

export const trendData: TrendDataPoint[] = generateTrendData();

// ====================================================================
// 3. Activity Feed Events (50 events)
// ====================================================================

export const activityEvents: ActivityEvent[] = [
  {
    id: "evt_001",
    type: "audit_completed",
    title: "Audit completed -- Food Safety, Downtown",
    description: "Score: 92% (Passed) -- 1 finding",
    module: "audits",
    actor_id: "user_003",
    actor_name: "Sarah Chen",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-14T11:45:00Z",
    severity: "info",
    link_to: "/audit/aud_001/results",
    source_id: "aud_001",
  },
  {
    id: "evt_002",
    type: "ticket_resolved",
    title: "Ticket TKT-00045 resolved",
    description: "Resolved by Maria Silva in 2h 15m",
    module: "tickets",
    actor_id: "user_001",
    actor_name: "Maria Silva",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-14T11:30:00Z",
    severity: "info",
    link_to: "/tickets/tkt_045",
    source_id: "tkt_045",
  },
  {
    id: "evt_003",
    type: "capa_overdue",
    title: "CAPA CAP-008 is overdue",
    description: "3 days past due date -- Freezer temperature control",
    module: "capa",
    actor_id: "user_002",
    actor_name: "Ahmed Khan",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-14T11:15:00Z",
    severity: "critical",
    link_to: "/capa/cap_008",
    source_id: "cap_008",
  },
  {
    id: "evt_004",
    type: "sla_breach",
    title: "SLA breach on TKT-00032",
    description: "Response time exceeded by 45 minutes",
    module: "sla",
    actor_id: "user_001",
    actor_name: "System",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-14T10:55:00Z",
    severity: "critical",
    link_to: "/tickets/tkt_032",
    source_id: "tkt_032",
  },
  {
    id: "evt_005",
    type: "task_completed",
    title: "Task completed: HVAC filter replacement",
    description: "Completed by Ahmed Khan -- 2 days ahead of schedule",
    module: "tasks",
    actor_id: "user_002",
    actor_name: "Ahmed Khan",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-14T10:30:00Z",
    severity: "info",
    link_to: "/tasks/tsk_012",
    source_id: "tsk_012",
  },
  {
    id: "evt_006",
    type: "audit_failed",
    title: "Audit failed -- Kitchen Hygiene, Airport",
    description: "Score: 62% (Failed) -- 5 findings",
    module: "audits",
    actor_id: "user_003",
    actor_name: "Sarah Chen",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-14T10:00:00Z",
    severity: "warning",
    link_to: "/audit/aud_005/results",
    source_id: "aud_005",
  },
  {
    id: "evt_007",
    type: "ticket_created",
    title: "New ticket: Broken AC unit in Room 304",
    description: "Reported by guest -- Priority: High",
    module: "tickets",
    actor_id: "user_004",
    actor_name: "James Wilson",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-14T09:45:00Z",
    severity: "warning",
    link_to: "/tickets/tkt_048",
    source_id: "tkt_048",
  },
  {
    id: "evt_008",
    type: "capa_created",
    title: "CAPA created from audit finding",
    description: "Improper chemical storage -- Kitchen area",
    module: "capa",
    actor_id: "user_003",
    actor_name: "Sarah Chen",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-14T09:15:00Z",
    severity: "warning",
    link_to: "/capa/cap_010",
    source_id: "cap_010",
  },
  {
    id: "evt_009",
    type: "sop_published",
    title: "SOP published: Emergency Evacuation v2.1",
    description: "Updated fire safety procedures -- 12 staff require acknowledgment",
    module: "sops",
    actor_id: "user_001",
    actor_name: "Maria Silva",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-14T08:30:00Z",
    severity: "info",
    link_to: "/sops/sop_003",
    source_id: "sop_003",
  },
  {
    id: "evt_010",
    type: "automation_fired",
    title: "Automation: Auto-escalated ticket TKT-00041",
    description: "Ticket priority elevated to Critical after 4h without response",
    module: "automation",
    actor_id: "user_001",
    actor_name: "System",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-14T08:00:00Z",
    severity: "warning",
    link_to: "/tickets/tkt_041",
    source_id: "tkt_041",
  },
  {
    id: "evt_011",
    type: "ticket_escalated",
    title: "Ticket TKT-00039 escalated to management",
    description: "Guest complaint unresolved for 24 hours",
    module: "tickets",
    actor_id: "user_004",
    actor_name: "James Wilson",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-13T18:30:00Z",
    severity: "critical",
    link_to: "/tickets/tkt_039",
    source_id: "tkt_039",
  },
  {
    id: "evt_012",
    type: "task_overdue",
    title: "Task overdue: Monthly fire extinguisher check",
    description: "Due 2 days ago -- Assigned to James Wilson",
    module: "tasks",
    actor_id: "user_004",
    actor_name: "James Wilson",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-13T17:00:00Z",
    severity: "warning",
    link_to: "/tasks/tsk_022",
    source_id: "tsk_022",
  },
  {
    id: "evt_013",
    type: "audit_completed",
    title: "Audit completed -- Room Cleanliness, Resort",
    description: "Score: 88% (Passed) -- 2 findings",
    module: "audits",
    actor_id: "user_001",
    actor_name: "Maria Silva",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-13T16:00:00Z",
    severity: "info",
    link_to: "/audit/aud_008/results",
    source_id: "aud_008",
  },
  {
    id: "evt_014",
    type: "ticket_resolved",
    title: "Ticket TKT-00038 resolved",
    description: "Resolved by Sarah Chen in 1h 30m",
    module: "tickets",
    actor_id: "user_003",
    actor_name: "Sarah Chen",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-13T15:30:00Z",
    severity: "info",
    link_to: "/tickets/tkt_038",
    source_id: "tkt_038",
  },
  {
    id: "evt_015",
    type: "capa_closed",
    title: "CAPA CAP-005 verified and closed",
    description: "Effectiveness review passed -- No recurrence in 30 days",
    module: "capa",
    actor_id: "user_001",
    actor_name: "Maria Silva",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-13T14:45:00Z",
    severity: "info",
    link_to: "/capa/cap_005",
    source_id: "cap_005",
  },
  {
    id: "evt_016",
    type: "task_completed",
    title: "Task completed: Update guest welcome protocols",
    description: "Completed on time by Maria Silva",
    module: "tasks",
    actor_id: "user_001",
    actor_name: "Maria Silva",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-13T14:00:00Z",
    severity: "info",
    link_to: "/tasks/tsk_015",
    source_id: "tsk_015",
  },
  {
    id: "evt_017",
    type: "ticket_created",
    title: "New ticket: WiFi outage in conference rooms",
    description: "Reported by staff -- Priority: Critical",
    module: "tickets",
    actor_id: "user_002",
    actor_name: "Ahmed Khan",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-13T12:15:00Z",
    severity: "critical",
    link_to: "/tickets/tkt_047",
    source_id: "tkt_047",
  },
  {
    id: "evt_018",
    type: "audit_completed",
    title: "Audit completed -- Fire Safety, Downtown",
    description: "Score: 95% (Passed) -- 0 findings",
    module: "audits",
    actor_id: "user_003",
    actor_name: "Sarah Chen",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-13T11:00:00Z",
    severity: "info",
    link_to: "/audit/aud_009/results",
    source_id: "aud_009",
  },
  {
    id: "evt_019",
    type: "sla_breach",
    title: "SLA breach on TKT-00035",
    description: "Resolution time exceeded by 2 hours",
    module: "sla",
    actor_id: "user_001",
    actor_name: "System",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-13T09:00:00Z",
    severity: "critical",
    link_to: "/tickets/tkt_035",
    source_id: "tkt_035",
  },
  {
    id: "evt_020",
    type: "ticket_resolved",
    title: "Ticket TKT-00034 resolved",
    description: "Resolved by James Wilson in 4h 10m",
    module: "tickets",
    actor_id: "user_004",
    actor_name: "James Wilson",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-13T08:00:00Z",
    severity: "info",
    link_to: "/tickets/tkt_034",
    source_id: "tkt_034",
  },
  {
    id: "evt_021",
    type: "task_completed",
    title: "Task completed: Pool chemical levels check",
    description: "Completed by Ahmed Khan",
    module: "tasks",
    actor_id: "user_002",
    actor_name: "Ahmed Khan",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-12T17:30:00Z",
    severity: "info",
    link_to: "/tasks/tsk_018",
    source_id: "tsk_018",
  },
  {
    id: "evt_022",
    type: "capa_overdue",
    title: "CAPA CAP-007 is overdue",
    description: "1 day past due -- Staff training on food handling",
    module: "capa",
    actor_id: "user_001",
    actor_name: "System",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-12T16:00:00Z",
    severity: "warning",
    link_to: "/capa/cap_007",
    source_id: "cap_007",
  },
  {
    id: "evt_023",
    type: "audit_completed",
    title: "Audit completed -- Guest Services, Airport",
    description: "Score: 78% (Passed) -- 3 findings",
    module: "audits",
    actor_id: "user_002",
    actor_name: "Ahmed Khan",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-12T14:45:00Z",
    severity: "info",
    link_to: "/audit/aud_010/results",
    source_id: "aud_010",
  },
  {
    id: "evt_024",
    type: "ticket_created",
    title: "New ticket: Elevator malfunction in lobby",
    description: "Reported by staff -- Priority: High",
    module: "tickets",
    actor_id: "user_001",
    actor_name: "Maria Silva",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-12T13:00:00Z",
    severity: "warning",
    link_to: "/tickets/tkt_046",
    source_id: "tkt_046",
  },
  {
    id: "evt_025",
    type: "ticket_resolved",
    title: "Ticket TKT-00030 resolved",
    description: "Resolved by Ahmed Khan in 3h 20m",
    module: "tickets",
    actor_id: "user_002",
    actor_name: "Ahmed Khan",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-12T11:30:00Z",
    severity: "info",
    link_to: "/tickets/tkt_030",
    source_id: "tkt_030",
  },
  {
    id: "evt_026",
    type: "audit_failed",
    title: "Audit failed -- Pool Safety, Resort",
    description: "Score: 58% (Failed) -- 7 findings",
    module: "audits",
    actor_id: "user_004",
    actor_name: "James Wilson",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-12T10:00:00Z",
    severity: "critical",
    link_to: "/audit/aud_011/results",
    source_id: "aud_011",
  },
  {
    id: "evt_027",
    type: "task_overdue",
    title: "Task overdue: Update emergency contact list",
    description: "Due 1 day ago -- Assigned to Sarah Chen",
    module: "tasks",
    actor_id: "user_003",
    actor_name: "Sarah Chen",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-12T08:00:00Z",
    severity: "warning",
    link_to: "/tasks/tsk_025",
    source_id: "tsk_025",
  },
  {
    id: "evt_028",
    type: "capa_created",
    title: "CAPA created: Pest control protocol update",
    description: "Manual entry -- Medium severity",
    module: "capa",
    actor_id: "user_001",
    actor_name: "Maria Silva",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-11T16:30:00Z",
    severity: "info",
    link_to: "/capa/cap_011",
    source_id: "cap_011",
  },
  {
    id: "evt_029",
    type: "ticket_resolved",
    title: "Ticket TKT-00028 resolved",
    description: "Resolved by Maria Silva in 5h 45m",
    module: "tickets",
    actor_id: "user_001",
    actor_name: "Maria Silva",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-11T15:00:00Z",
    severity: "info",
    link_to: "/tickets/tkt_028",
    source_id: "tkt_028",
  },
  {
    id: "evt_030",
    type: "automation_fired",
    title: "Automation: Weekly compliance report generated",
    description: "Sent to 5 recipients",
    module: "automation",
    actor_id: "user_001",
    actor_name: "System",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-11T08:00:00Z",
    severity: "info",
    link_to: "/workflow",
    source_id: "rule_002",
  },
  {
    id: "evt_031",
    type: "audit_completed",
    title: "Audit completed -- Lobby Maintenance, Downtown",
    description: "Score: 90% (Passed) -- 1 finding",
    module: "audits",
    actor_id: "user_001",
    actor_name: "Maria Silva",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-11T14:00:00Z",
    severity: "info",
    link_to: "/audit/aud_012/results",
    source_id: "aud_012",
  },
  {
    id: "evt_032",
    type: "ticket_created",
    title: "New ticket: Stained carpet in hallway",
    description: "Reported by housekeeping -- Priority: Medium",
    module: "tickets",
    actor_id: "user_003",
    actor_name: "Sarah Chen",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-11T12:00:00Z",
    severity: "info",
    link_to: "/tickets/tkt_044",
    source_id: "tkt_044",
  },
  {
    id: "evt_033",
    type: "capa_closed",
    title: "CAPA CAP-003 closed successfully",
    description: "Training completed for all staff",
    module: "capa",
    actor_id: "user_002",
    actor_name: "Ahmed Khan",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-11T10:30:00Z",
    severity: "info",
    link_to: "/capa/cap_003",
    source_id: "cap_003",
  },
  {
    id: "evt_034",
    type: "task_completed",
    title: "Task completed: Quarterly safety drill",
    description: "All staff participated -- Completed on time",
    module: "tasks",
    actor_id: "user_004",
    actor_name: "James Wilson",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-10T16:00:00Z",
    severity: "info",
    link_to: "/tasks/tsk_020",
    source_id: "tsk_020",
  },
  {
    id: "evt_035",
    type: "sla_breach",
    title: "SLA breach on TKT-00029",
    description: "First response time exceeded by 30 minutes",
    module: "sla",
    actor_id: "user_001",
    actor_name: "System",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-10T14:00:00Z",
    severity: "warning",
    link_to: "/tickets/tkt_029",
    source_id: "tkt_029",
  },
  {
    id: "evt_036",
    type: "ticket_resolved",
    title: "Ticket TKT-00027 resolved",
    description: "Resolved by James Wilson in 1h 45m",
    module: "tickets",
    actor_id: "user_004",
    actor_name: "James Wilson",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-10T12:00:00Z",
    severity: "info",
    link_to: "/tickets/tkt_027",
    source_id: "tkt_027",
  },
  {
    id: "evt_037",
    type: "audit_completed",
    title: "Audit completed -- Housekeeping Standards, Airport",
    description: "Score: 81% (Passed) -- 3 findings",
    module: "audits",
    actor_id: "user_002",
    actor_name: "Ahmed Khan",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-10T10:00:00Z",
    severity: "info",
    link_to: "/audit/aud_013/results",
    source_id: "aud_013",
  },
  {
    id: "evt_038",
    type: "ticket_created",
    title: "New ticket: Water leak in basement storage",
    description: "Reported by maintenance -- Priority: Critical",
    module: "tickets",
    actor_id: "user_002",
    actor_name: "Ahmed Khan",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-10T09:00:00Z",
    severity: "critical",
    link_to: "/tickets/tkt_043",
    source_id: "tkt_043",
  },
  {
    id: "evt_039",
    type: "capa_overdue",
    title: "CAPA CAP-006 is overdue",
    description: "5 days past due -- Equipment calibration",
    module: "capa",
    actor_id: "user_001",
    actor_name: "System",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-09T17:00:00Z",
    severity: "critical",
    link_to: "/capa/cap_006",
    source_id: "cap_006",
  },
  {
    id: "evt_040",
    type: "task_completed",
    title: "Task completed: Restock first aid kits",
    description: "Completed by Sarah Chen",
    module: "tasks",
    actor_id: "user_003",
    actor_name: "Sarah Chen",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-09T15:00:00Z",
    severity: "info",
    link_to: "/tasks/tsk_019",
    source_id: "tsk_019",
  },
  {
    id: "evt_041",
    type: "ticket_resolved",
    title: "Ticket TKT-00025 resolved",
    description: "Resolved by Ahmed Khan in 6h 30m",
    module: "tickets",
    actor_id: "user_002",
    actor_name: "Ahmed Khan",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-09T14:00:00Z",
    severity: "info",
    link_to: "/tickets/tkt_025",
    source_id: "tkt_025",
  },
  {
    id: "evt_042",
    type: "audit_completed",
    title: "Audit completed -- Breakfast Service, Resort",
    description: "Score: 85% (Passed) -- 2 findings",
    module: "audits",
    actor_id: "user_004",
    actor_name: "James Wilson",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-09T11:00:00Z",
    severity: "info",
    link_to: "/audit/aud_014/results",
    source_id: "aud_014",
  },
  {
    id: "evt_043",
    type: "sop_published",
    title: "SOP published: Pool Maintenance v1.3",
    description: "Updated chemical handling procedures",
    module: "sops",
    actor_id: "user_004",
    actor_name: "James Wilson",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-09T09:00:00Z",
    severity: "info",
    link_to: "/sops/sop_005",
    source_id: "sop_005",
  },
  {
    id: "evt_044",
    type: "ticket_created",
    title: "New ticket: Noise complaint from Room 502",
    description: "Reported by front desk -- Priority: Medium",
    module: "tickets",
    actor_id: "user_001",
    actor_name: "Maria Silva",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-08T22:30:00Z",
    severity: "info",
    link_to: "/tickets/tkt_042",
    source_id: "tkt_042",
  },
  {
    id: "evt_045",
    type: "capa_created",
    title: "CAPA created from ticket escalation",
    description: "Recurring plumbing issues -- Downtown location",
    module: "capa",
    actor_id: "user_001",
    actor_name: "Maria Silva",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-08T16:00:00Z",
    severity: "warning",
    link_to: "/capa/cap_009",
    source_id: "cap_009",
  },
  {
    id: "evt_046",
    type: "task_overdue",
    title: "Task overdue: Deep clean kitchen hoods",
    description: "Due 3 days ago -- Assigned to Ahmed Khan",
    module: "tasks",
    actor_id: "user_002",
    actor_name: "Ahmed Khan",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-08T08:00:00Z",
    severity: "warning",
    link_to: "/tasks/tsk_023",
    source_id: "tsk_023",
  },
  {
    id: "evt_047",
    type: "audit_completed",
    title: "Audit completed -- Front Desk Standards, Downtown",
    description: "Score: 94% (Passed) -- 0 findings",
    module: "audits",
    actor_id: "user_001",
    actor_name: "Maria Silva",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-08T14:00:00Z",
    severity: "info",
    link_to: "/audit/aud_015/results",
    source_id: "aud_015",
  },
  {
    id: "evt_048",
    type: "ticket_resolved",
    title: "Ticket TKT-00022 resolved",
    description: "Resolved by Sarah Chen in 45m",
    module: "tickets",
    actor_id: "user_003",
    actor_name: "Sarah Chen",
    location_id: "loc_001",
    location_name: "Downtown",
    timestamp: "2026-03-08T12:00:00Z",
    severity: "info",
    link_to: "/tickets/tkt_022",
    source_id: "tkt_022",
  },
  {
    id: "evt_049",
    type: "automation_fired",
    title: "Automation: Created task from audit finding",
    description: "Pool safety finding auto-generated maintenance task",
    module: "automation",
    actor_id: "user_001",
    actor_name: "System",
    location_id: "loc_003",
    location_name: "Resort",
    timestamp: "2026-03-08T10:00:00Z",
    severity: "info",
    link_to: "/tasks/tsk_024",
    source_id: "tsk_024",
  },
  {
    id: "evt_050",
    type: "capa_closed",
    title: "CAPA CAP-002 verified and closed",
    description: "Effectiveness confirmed -- Chemical storage improved",
    module: "capa",
    actor_id: "user_003",
    actor_name: "Sarah Chen",
    location_id: "loc_002",
    location_name: "Airport",
    timestamp: "2026-03-07T16:00:00Z",
    severity: "info",
    link_to: "/capa/cap_002",
    source_id: "cap_002",
  },
];

// ====================================================================
// 4. Location Tree (1 org, 3 regions, 9 stores)
// ====================================================================

export const locationTree: LocationNode = {
  id: "org_001",
  name: "Acme Hotels",
  type: "org",
  parent_id: null,
  metrics: {
    compliance_score: 87,
    open_tickets: 23,
    open_capas: 18,
    overdue_tasks: 11,
    audits_this_period: 47,
    avg_resolution_hours: 4.2,
    sla_compliance_pct: 94,
    csat_score: 4.2,
  },
  children: [
    {
      id: "reg_east",
      name: "East Region",
      type: "region",
      parent_id: "org_001",
      metrics: {
        compliance_score: 91,
        open_tickets: 8,
        open_capas: 5,
        overdue_tasks: 3,
        audits_this_period: 18,
        avg_resolution_hours: 3.5,
        sla_compliance_pct: 96,
        csat_score: 4.4,
      },
      children: [
        {
          id: "loc_001",
          name: "Downtown",
          type: "store",
          parent_id: "reg_east",
          metrics: {
            compliance_score: 92,
            open_tickets: 5,
            open_capas: 2,
            overdue_tasks: 1,
            audits_this_period: 8,
            avg_resolution_hours: 3.2,
            sla_compliance_pct: 97,
            csat_score: 4.5,
          },
        },
        {
          id: "loc_004",
          name: "Marina",
          type: "store",
          parent_id: "reg_east",
          metrics: {
            compliance_score: 89,
            open_tickets: 2,
            open_capas: 2,
            overdue_tasks: 1,
            audits_this_period: 5,
            avg_resolution_hours: 3.8,
            sla_compliance_pct: 95,
            csat_score: 4.3,
          },
        },
        {
          id: "loc_005",
          name: "Uptown",
          type: "store",
          parent_id: "reg_east",
          metrics: {
            compliance_score: 93,
            open_tickets: 1,
            open_capas: 1,
            overdue_tasks: 1,
            audits_this_period: 5,
            avg_resolution_hours: 3.4,
            sla_compliance_pct: 96,
            csat_score: 4.4,
          },
        },
      ],
    },
    {
      id: "reg_west",
      name: "West Region",
      type: "region",
      parent_id: "org_001",
      metrics: {
        compliance_score: 86,
        open_tickets: 7,
        open_capas: 6,
        overdue_tasks: 4,
        audits_this_period: 14,
        avg_resolution_hours: 4.5,
        sla_compliance_pct: 92,
        csat_score: 4.1,
      },
      children: [
        {
          id: "loc_002",
          name: "Airport",
          type: "store",
          parent_id: "reg_west",
          metrics: {
            compliance_score: 78,
            open_tickets: 4,
            open_capas: 3,
            overdue_tasks: 2,
            audits_this_period: 6,
            avg_resolution_hours: 5.1,
            sla_compliance_pct: 89,
            csat_score: 3.8,
          },
        },
        {
          id: "loc_006",
          name: "Riverside",
          type: "store",
          parent_id: "reg_west",
          metrics: {
            compliance_score: 90,
            open_tickets: 2,
            open_capas: 2,
            overdue_tasks: 1,
            audits_this_period: 4,
            avg_resolution_hours: 3.9,
            sla_compliance_pct: 94,
            csat_score: 4.2,
          },
        },
        {
          id: "loc_007",
          name: "Hillside",
          type: "store",
          parent_id: "reg_west",
          metrics: {
            compliance_score: 88,
            open_tickets: 1,
            open_capas: 1,
            overdue_tasks: 1,
            audits_this_period: 4,
            avg_resolution_hours: 4.4,
            sla_compliance_pct: 93,
            csat_score: 4.3,
          },
        },
      ],
    },
    {
      id: "reg_south",
      name: "South Region",
      type: "region",
      parent_id: "org_001",
      metrics: {
        compliance_score: 84,
        open_tickets: 8,
        open_capas: 7,
        overdue_tasks: 4,
        audits_this_period: 15,
        avg_resolution_hours: 4.8,
        sla_compliance_pct: 91,
        csat_score: 4.0,
      },
      children: [
        {
          id: "loc_003",
          name: "Resort",
          type: "store",
          parent_id: "reg_south",
          metrics: {
            compliance_score: 88,
            open_tickets: 3,
            open_capas: 2,
            overdue_tasks: 1,
            audits_this_period: 6,
            avg_resolution_hours: 4.3,
            sla_compliance_pct: 92,
            csat_score: 4.1,
          },
        },
        {
          id: "loc_008",
          name: "Beachside",
          type: "store",
          parent_id: "reg_south",
          metrics: {
            compliance_score: 82,
            open_tickets: 3,
            open_capas: 3,
            overdue_tasks: 2,
            audits_this_period: 5,
            avg_resolution_hours: 5.2,
            sla_compliance_pct: 88,
            csat_score: 3.9,
          },
        },
        {
          id: "loc_009",
          name: "Harbor",
          type: "store",
          parent_id: "reg_south",
          metrics: {
            compliance_score: 86,
            open_tickets: 2,
            open_capas: 2,
            overdue_tasks: 1,
            audits_this_period: 4,
            avg_resolution_hours: 4.6,
            sla_compliance_pct: 93,
            csat_score: 4.0,
          },
        },
      ],
    },
  ],
};

// ====================================================================
// 5. Ticket Analytics (6 months)
// ====================================================================

export const ticketAnalytics: TicketAnalytics[] = [
  {
    period: "2025-10",
    created: 28,
    resolved: 25,
    escalated: 3,
    avg_resolution_hours: 5.2,
    avg_first_response_hours: 0.8,
    sla_met: 22,
    sla_breached: 6,
    by_category: [
      { category: "F&B", count: 8, color: "#58A6FF" },
      { category: "Housekeeping", count: 7, color: "#3FB950" },
      { category: "Maintenance", count: 6, color: "#D29922" },
      { category: "Compliance", count: 4, color: "#F85149" },
      { category: "Guest Relations", count: 3, color: "#BC8CFF" },
    ],
    by_priority: [
      { priority: "Critical", count: 3, color: "#F85149" },
      { priority: "High", count: 8, color: "#D29922" },
      { priority: "Medium", count: 12, color: "#58A6FF" },
      { priority: "Low", count: 5, color: "#8B949E" },
    ],
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", count: 10 },
      { location_id: "loc_002", location_name: "Airport", count: 9 },
      { location_id: "loc_003", location_name: "Resort", count: 9 },
    ],
    csat_avg: 3.9,
    csat_responses: 18,
  },
  {
    period: "2025-11",
    created: 32,
    resolved: 29,
    escalated: 4,
    avg_resolution_hours: 4.8,
    avg_first_response_hours: 0.7,
    sla_met: 26,
    sla_breached: 6,
    by_category: [
      { category: "F&B", count: 9, color: "#58A6FF" },
      { category: "Housekeeping", count: 8, color: "#3FB950" },
      { category: "Maintenance", count: 7, color: "#D29922" },
      { category: "Compliance", count: 5, color: "#F85149" },
      { category: "Guest Relations", count: 3, color: "#BC8CFF" },
    ],
    by_priority: [
      { priority: "Critical", count: 4, color: "#F85149" },
      { priority: "High", count: 9, color: "#D29922" },
      { priority: "Medium", count: 14, color: "#58A6FF" },
      { priority: "Low", count: 5, color: "#8B949E" },
    ],
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", count: 12 },
      { location_id: "loc_002", location_name: "Airport", count: 11 },
      { location_id: "loc_003", location_name: "Resort", count: 9 },
    ],
    csat_avg: 4.0,
    csat_responses: 22,
  },
  {
    period: "2025-12",
    created: 35,
    resolved: 30,
    escalated: 5,
    avg_resolution_hours: 4.5,
    avg_first_response_hours: 0.6,
    sla_met: 27,
    sla_breached: 8,
    by_category: [
      { category: "F&B", count: 10, color: "#58A6FF" },
      { category: "Housekeeping", count: 9, color: "#3FB950" },
      { category: "Maintenance", count: 8, color: "#D29922" },
      { category: "Compliance", count: 5, color: "#F85149" },
      { category: "Guest Relations", count: 3, color: "#BC8CFF" },
    ],
    by_priority: [
      { priority: "Critical", count: 5, color: "#F85149" },
      { priority: "High", count: 10, color: "#D29922" },
      { priority: "Medium", count: 15, color: "#58A6FF" },
      { priority: "Low", count: 5, color: "#8B949E" },
    ],
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", count: 13 },
      { location_id: "loc_002", location_name: "Airport", count: 12 },
      { location_id: "loc_003", location_name: "Resort", count: 10 },
    ],
    csat_avg: 4.1,
    csat_responses: 25,
  },
  {
    period: "2026-01",
    created: 30,
    resolved: 28,
    escalated: 3,
    avg_resolution_hours: 4.3,
    avg_first_response_hours: 0.5,
    sla_met: 25,
    sla_breached: 5,
    by_category: [
      { category: "F&B", count: 8, color: "#58A6FF" },
      { category: "Housekeeping", count: 8, color: "#3FB950" },
      { category: "Maintenance", count: 7, color: "#D29922" },
      { category: "Compliance", count: 4, color: "#F85149" },
      { category: "Guest Relations", count: 3, color: "#BC8CFF" },
    ],
    by_priority: [
      { priority: "Critical", count: 3, color: "#F85149" },
      { priority: "High", count: 8, color: "#D29922" },
      { priority: "Medium", count: 14, color: "#58A6FF" },
      { priority: "Low", count: 5, color: "#8B949E" },
    ],
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", count: 11 },
      { location_id: "loc_002", location_name: "Airport", count: 10 },
      { location_id: "loc_003", location_name: "Resort", count: 9 },
    ],
    csat_avg: 4.1,
    csat_responses: 20,
  },
  {
    period: "2026-02",
    created: 26,
    resolved: 24,
    escalated: 2,
    avg_resolution_hours: 4.0,
    avg_first_response_hours: 0.5,
    sla_met: 22,
    sla_breached: 4,
    by_category: [
      { category: "F&B", count: 7, color: "#58A6FF" },
      { category: "Housekeeping", count: 7, color: "#3FB950" },
      { category: "Maintenance", count: 6, color: "#D29922" },
      { category: "Compliance", count: 4, color: "#F85149" },
      { category: "Guest Relations", count: 2, color: "#BC8CFF" },
    ],
    by_priority: [
      { priority: "Critical", count: 2, color: "#F85149" },
      { priority: "High", count: 7, color: "#D29922" },
      { priority: "Medium", count: 12, color: "#58A6FF" },
      { priority: "Low", count: 5, color: "#8B949E" },
    ],
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", count: 10 },
      { location_id: "loc_002", location_name: "Airport", count: 9 },
      { location_id: "loc_003", location_name: "Resort", count: 7 },
    ],
    csat_avg: 4.2,
    csat_responses: 19,
  },
  {
    period: "2026-03",
    created: 23,
    resolved: 18,
    escalated: 2,
    avg_resolution_hours: 4.2,
    avg_first_response_hours: 0.4,
    sla_met: 17,
    sla_breached: 3,
    by_category: [
      { category: "F&B", count: 6, color: "#58A6FF" },
      { category: "Housekeeping", count: 6, color: "#3FB950" },
      { category: "Maintenance", count: 5, color: "#D29922" },
      { category: "Compliance", count: 4, color: "#F85149" },
      { category: "Guest Relations", count: 2, color: "#BC8CFF" },
    ],
    by_priority: [
      { priority: "Critical", count: 2, color: "#F85149" },
      { priority: "High", count: 6, color: "#D29922" },
      { priority: "Medium", count: 11, color: "#58A6FF" },
      { priority: "Low", count: 4, color: "#8B949E" },
    ],
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", count: 9 },
      { location_id: "loc_002", location_name: "Airport", count: 8 },
      { location_id: "loc_003", location_name: "Resort", count: 6 },
    ],
    csat_avg: 4.2,
    csat_responses: 15,
  },
];

// ====================================================================
// 6. Audit Analytics (6 months)
// ====================================================================

export const auditAnalytics: AuditAnalytics[] = [
  {
    period: "2025-10",
    audits_completed: 6,
    audits_scheduled: 8,
    avg_score: 82,
    pass_rate: 72,
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", avg_score: 92, audit_count: 3, pass_rate: 100 },
      { location_id: "loc_002", location_name: "Airport", avg_score: 75, audit_count: 2, pass_rate: 50 },
      { location_id: "loc_003", location_name: "Resort", avg_score: 85, audit_count: 1, pass_rate: 100 },
    ],
    by_category: [
      { category: "Food Safety", avg_score: 80, count: 2 },
      { category: "Room Standards", avg_score: 88, count: 2 },
      { category: "Fire Safety", avg_score: 78, count: 2 },
    ],
    findings_count: 12,
    auto_tickets_created: 4,
    auto_capas_created: 2,
    score_trend: [{ date: "2025-10", score: 82 }],
  },
  {
    period: "2025-11",
    audits_completed: 7,
    audits_scheduled: 8,
    avg_score: 80,
    pass_rate: 71,
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", avg_score: 88, audit_count: 3, pass_rate: 100 },
      { location_id: "loc_002", location_name: "Airport", avg_score: 72, audit_count: 2, pass_rate: 50 },
      { location_id: "loc_003", location_name: "Resort", avg_score: 87, audit_count: 2, pass_rate: 100 },
    ],
    by_category: [
      { category: "Food Safety", avg_score: 77, count: 3 },
      { category: "Room Standards", avg_score: 85, count: 2 },
      { category: "Fire Safety", avg_score: 82, count: 2 },
    ],
    findings_count: 15,
    auto_tickets_created: 5,
    auto_capas_created: 3,
    score_trend: [{ date: "2025-11", score: 80 }],
  },
  {
    period: "2025-12",
    audits_completed: 8,
    audits_scheduled: 9,
    avg_score: 83,
    pass_rate: 75,
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", avg_score: 91, audit_count: 3, pass_rate: 100 },
      { location_id: "loc_002", location_name: "Airport", avg_score: 78, audit_count: 3, pass_rate: 67 },
      { location_id: "loc_003", location_name: "Resort", avg_score: 83, audit_count: 2, pass_rate: 50 },
    ],
    by_category: [
      { category: "Food Safety", avg_score: 81, count: 3 },
      { category: "Room Standards", avg_score: 87, count: 3 },
      { category: "Fire Safety", avg_score: 80, count: 2 },
    ],
    findings_count: 14,
    auto_tickets_created: 5,
    auto_capas_created: 2,
    score_trend: [{ date: "2025-12", score: 83 }],
  },
  {
    period: "2026-01",
    audits_completed: 8,
    audits_scheduled: 9,
    avg_score: 81,
    pass_rate: 75,
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", avg_score: 85, audit_count: 3, pass_rate: 100 },
      { location_id: "loc_002", location_name: "Airport", avg_score: 80, audit_count: 3, pass_rate: 67 },
      { location_id: "loc_003", location_name: "Resort", avg_score: 88, audit_count: 2, pass_rate: 100 },
    ],
    by_category: [
      { category: "Food Safety", avg_score: 79, count: 3 },
      { category: "Room Standards", avg_score: 84, count: 3 },
      { category: "Fire Safety", avg_score: 82, count: 2 },
    ],
    findings_count: 10,
    auto_tickets_created: 3,
    auto_capas_created: 2,
    score_trend: [{ date: "2026-01", score: 81 }],
  },
  {
    period: "2026-02",
    audits_completed: 9,
    audits_scheduled: 10,
    avg_score: 85,
    pass_rate: 78,
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", avg_score: 90, audit_count: 3, pass_rate: 100 },
      { location_id: "loc_002", location_name: "Airport", avg_score: 76, audit_count: 3, pass_rate: 67 },
      { location_id: "loc_003", location_name: "Resort", avg_score: 86, audit_count: 3, pass_rate: 67 },
    ],
    by_category: [
      { category: "Food Safety", avg_score: 83, count: 3 },
      { category: "Room Standards", avg_score: 89, count: 3 },
      { category: "Fire Safety", avg_score: 84, count: 3 },
    ],
    findings_count: 11,
    auto_tickets_created: 4,
    auto_capas_created: 2,
    score_trend: [{ date: "2026-02", score: 85 }],
  },
  {
    period: "2026-03",
    audits_completed: 9,
    audits_scheduled: 10,
    avg_score: 84,
    pass_rate: 78,
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", avg_score: 92, audit_count: 3, pass_rate: 100 },
      { location_id: "loc_002", location_name: "Airport", avg_score: 78, audit_count: 3, pass_rate: 67 },
      { location_id: "loc_003", location_name: "Resort", avg_score: 88, audit_count: 3, pass_rate: 67 },
    ],
    by_category: [
      { category: "Food Safety", avg_score: 82, count: 3 },
      { category: "Room Standards", avg_score: 88, count: 3 },
      { category: "Fire Safety", avg_score: 85, count: 3 },
    ],
    findings_count: 8,
    auto_tickets_created: 3,
    auto_capas_created: 1,
    score_trend: [{ date: "2026-03", score: 84 }],
  },
];

// ====================================================================
// 7. CAPA Analytics (6 months)
// ====================================================================

export const capaAnalytics: CAPAAnalytics[] = [
  {
    period: "2025-10",
    total_open: 12,
    total_closed: 5,
    avg_closure_days: 14,
    overdue_count: 3,
    by_severity: [
      { severity: "Critical", count: 2, color: "#F85149" },
      { severity: "High", count: 4, color: "#D29922" },
      { severity: "Medium", count: 4, color: "#58A6FF" },
      { severity: "Low", count: 2, color: "#8B949E" },
    ],
    by_source: [
      { source: "Audit", count: 6, color: "#3FB950" },
      { source: "Ticket", count: 4, color: "#58A6FF" },
      { source: "Manual", count: 2, color: "#BC8CFF" },
    ],
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", open: 4, closed: 2, overdue: 1 },
      { location_id: "loc_002", location_name: "Airport", open: 5, closed: 2, overdue: 1 },
      { location_id: "loc_003", location_name: "Resort", open: 3, closed: 1, overdue: 1 },
    ],
    closure_trend: [{ date: "2025-10", closed: 5, opened: 7 }],
    recurrence_rate: 15,
    effectiveness_rate: 80,
  },
  {
    period: "2025-11",
    total_open: 14,
    total_closed: 6,
    avg_closure_days: 13,
    overdue_count: 4,
    by_severity: [
      { severity: "Critical", count: 3, color: "#F85149" },
      { severity: "High", count: 5, color: "#D29922" },
      { severity: "Medium", count: 4, color: "#58A6FF" },
      { severity: "Low", count: 2, color: "#8B949E" },
    ],
    by_source: [
      { source: "Audit", count: 7, color: "#3FB950" },
      { source: "Ticket", count: 5, color: "#58A6FF" },
      { source: "Manual", count: 2, color: "#BC8CFF" },
    ],
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", open: 5, closed: 2, overdue: 1 },
      { location_id: "loc_002", location_name: "Airport", open: 5, closed: 2, overdue: 2 },
      { location_id: "loc_003", location_name: "Resort", open: 4, closed: 2, overdue: 1 },
    ],
    closure_trend: [{ date: "2025-11", closed: 6, opened: 8 }],
    recurrence_rate: 18,
    effectiveness_rate: 75,
  },
  {
    period: "2025-12",
    total_open: 16,
    total_closed: 7,
    avg_closure_days: 12,
    overdue_count: 5,
    by_severity: [
      { severity: "Critical", count: 3, color: "#F85149" },
      { severity: "High", count: 5, color: "#D29922" },
      { severity: "Medium", count: 5, color: "#58A6FF" },
      { severity: "Low", count: 3, color: "#8B949E" },
    ],
    by_source: [
      { source: "Audit", count: 8, color: "#3FB950" },
      { source: "Ticket", count: 5, color: "#58A6FF" },
      { source: "Manual", count: 3, color: "#BC8CFF" },
    ],
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", open: 5, closed: 3, overdue: 2 },
      { location_id: "loc_002", location_name: "Airport", open: 6, closed: 2, overdue: 2 },
      { location_id: "loc_003", location_name: "Resort", open: 5, closed: 2, overdue: 1 },
    ],
    closure_trend: [{ date: "2025-12", closed: 7, opened: 9 }],
    recurrence_rate: 16,
    effectiveness_rate: 78,
  },
  {
    period: "2026-01",
    total_open: 15,
    total_closed: 8,
    avg_closure_days: 11,
    overdue_count: 4,
    by_severity: [
      { severity: "Critical", count: 2, color: "#F85149" },
      { severity: "High", count: 5, color: "#D29922" },
      { severity: "Medium", count: 5, color: "#58A6FF" },
      { severity: "Low", count: 3, color: "#8B949E" },
    ],
    by_source: [
      { source: "Audit", count: 7, color: "#3FB950" },
      { source: "Ticket", count: 5, color: "#58A6FF" },
      { source: "Manual", count: 3, color: "#BC8CFF" },
    ],
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", open: 5, closed: 3, overdue: 1 },
      { location_id: "loc_002", location_name: "Airport", open: 5, closed: 3, overdue: 2 },
      { location_id: "loc_003", location_name: "Resort", open: 5, closed: 2, overdue: 1 },
    ],
    closure_trend: [{ date: "2026-01", closed: 8, opened: 7 }],
    recurrence_rate: 14,
    effectiveness_rate: 82,
  },
  {
    period: "2026-02",
    total_open: 14,
    total_closed: 7,
    avg_closure_days: 12,
    overdue_count: 3,
    by_severity: [
      { severity: "Critical", count: 2, color: "#F85149" },
      { severity: "High", count: 4, color: "#D29922" },
      { severity: "Medium", count: 5, color: "#58A6FF" },
      { severity: "Low", count: 3, color: "#8B949E" },
    ],
    by_source: [
      { source: "Audit", count: 6, color: "#3FB950" },
      { source: "Ticket", count: 5, color: "#58A6FF" },
      { source: "Manual", count: 3, color: "#BC8CFF" },
    ],
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", open: 4, closed: 3, overdue: 1 },
      { location_id: "loc_002", location_name: "Airport", open: 5, closed: 2, overdue: 1 },
      { location_id: "loc_003", location_name: "Resort", open: 5, closed: 2, overdue: 1 },
    ],
    closure_trend: [{ date: "2026-02", closed: 7, opened: 6 }],
    recurrence_rate: 12,
    effectiveness_rate: 85,
  },
  {
    period: "2026-03",
    total_open: 18,
    total_closed: 6,
    avg_closure_days: 12,
    overdue_count: 4,
    by_severity: [
      { severity: "Critical", count: 3, color: "#F85149" },
      { severity: "High", count: 6, color: "#D29922" },
      { severity: "Medium", count: 6, color: "#58A6FF" },
      { severity: "Low", count: 3, color: "#8B949E" },
    ],
    by_source: [
      { source: "Audit", count: 9, color: "#3FB950" },
      { source: "Ticket", count: 6, color: "#58A6FF" },
      { source: "Manual", count: 3, color: "#BC8CFF" },
    ],
    by_location: [
      { location_id: "loc_001", location_name: "Downtown", open: 6, closed: 2, overdue: 1 },
      { location_id: "loc_002", location_name: "Airport", open: 6, closed: 2, overdue: 2 },
      { location_id: "loc_003", location_name: "Resort", open: 6, closed: 2, overdue: 1 },
    ],
    closure_trend: [{ date: "2026-03", closed: 6, opened: 8 }],
    recurrence_rate: 13,
    effectiveness_rate: 83,
  },
];

// ====================================================================
// 8. Task Analytics (6 months)
// ====================================================================

export const taskAnalytics: TaskAnalytics[] = [
  {
    period: "2025-10",
    total_created: 15,
    total_completed: 12,
    total_overdue: 3,
    avg_completion_days: 5,
    velocity: 3,
    by_assignee: [
      { user_id: "user_001", user_name: "Maria Silva", assigned: 5, completed: 4, overdue: 1 },
      { user_id: "user_002", user_name: "Ahmed Khan", assigned: 4, completed: 3, overdue: 1 },
      { user_id: "user_003", user_name: "Sarah Chen", assigned: 3, completed: 3, overdue: 0 },
      { user_id: "user_004", user_name: "James Wilson", assigned: 3, completed: 2, overdue: 1 },
    ],
    by_source: [
      { source: "Manual", count: 6, color: "#58A6FF" },
      { source: "Audit", count: 4, color: "#3FB950" },
      { source: "CAPA", count: 3, color: "#D29922" },
      { source: "Ticket", count: 2, color: "#BC8CFF" },
    ],
    by_status: [
      { status: "Done", count: 12, color: "#3FB950" },
      { status: "In Progress", count: 2, color: "#58A6FF" },
      { status: "Todo", count: 1, color: "#8B949E" },
    ],
    completion_trend: [
      { date: "W40", completed: 3, created: 4 },
      { date: "W41", completed: 3, created: 3 },
      { date: "W42", completed: 3, created: 4 },
      { date: "W43", completed: 3, created: 4 },
    ],
    overdue_trend: [
      { date: "W40", overdue: 1, on_time: 3 },
      { date: "W41", overdue: 0, on_time: 3 },
      { date: "W42", overdue: 1, on_time: 2 },
      { date: "W43", overdue: 1, on_time: 2 },
    ],
  },
  {
    period: "2025-11",
    total_created: 18,
    total_completed: 14,
    total_overdue: 4,
    avg_completion_days: 4.5,
    velocity: 3.5,
    by_assignee: [
      { user_id: "user_001", user_name: "Maria Silva", assigned: 6, completed: 5, overdue: 1 },
      { user_id: "user_002", user_name: "Ahmed Khan", assigned: 5, completed: 4, overdue: 1 },
      { user_id: "user_003", user_name: "Sarah Chen", assigned: 4, completed: 3, overdue: 1 },
      { user_id: "user_004", user_name: "James Wilson", assigned: 3, completed: 2, overdue: 1 },
    ],
    by_source: [
      { source: "Manual", count: 7, color: "#58A6FF" },
      { source: "Audit", count: 5, color: "#3FB950" },
      { source: "CAPA", count: 4, color: "#D29922" },
      { source: "Ticket", count: 2, color: "#BC8CFF" },
    ],
    by_status: [
      { status: "Done", count: 14, color: "#3FB950" },
      { status: "In Progress", count: 3, color: "#58A6FF" },
      { status: "Todo", count: 1, color: "#8B949E" },
    ],
    completion_trend: [
      { date: "W44", completed: 3, created: 4 },
      { date: "W45", completed: 4, created: 5 },
      { date: "W46", completed: 3, created: 4 },
      { date: "W47", completed: 4, created: 5 },
    ],
    overdue_trend: [
      { date: "W44", overdue: 1, on_time: 2 },
      { date: "W45", overdue: 1, on_time: 3 },
      { date: "W46", overdue: 1, on_time: 2 },
      { date: "W47", overdue: 1, on_time: 3 },
    ],
  },
  {
    period: "2025-12",
    total_created: 20,
    total_completed: 16,
    total_overdue: 4,
    avg_completion_days: 4.2,
    velocity: 4,
    by_assignee: [
      { user_id: "user_001", user_name: "Maria Silva", assigned: 7, completed: 5, overdue: 1 },
      { user_id: "user_002", user_name: "Ahmed Khan", assigned: 5, completed: 4, overdue: 1 },
      { user_id: "user_003", user_name: "Sarah Chen", assigned: 4, completed: 4, overdue: 1 },
      { user_id: "user_004", user_name: "James Wilson", assigned: 4, completed: 3, overdue: 1 },
    ],
    by_source: [
      { source: "Manual", count: 8, color: "#58A6FF" },
      { source: "Audit", count: 5, color: "#3FB950" },
      { source: "CAPA", count: 4, color: "#D29922" },
      { source: "Ticket", count: 3, color: "#BC8CFF" },
    ],
    by_status: [
      { status: "Done", count: 16, color: "#3FB950" },
      { status: "In Progress", count: 3, color: "#58A6FF" },
      { status: "Todo", count: 1, color: "#8B949E" },
    ],
    completion_trend: [
      { date: "W48", completed: 4, created: 5 },
      { date: "W49", completed: 4, created: 5 },
      { date: "W50", completed: 4, created: 5 },
      { date: "W51", completed: 4, created: 5 },
    ],
    overdue_trend: [
      { date: "W48", overdue: 1, on_time: 3 },
      { date: "W49", overdue: 1, on_time: 3 },
      { date: "W50", overdue: 1, on_time: 3 },
      { date: "W51", overdue: 1, on_time: 3 },
    ],
  },
  {
    period: "2026-01",
    total_created: 17,
    total_completed: 15,
    total_overdue: 3,
    avg_completion_days: 4.0,
    velocity: 3.8,
    by_assignee: [
      { user_id: "user_001", user_name: "Maria Silva", assigned: 5, completed: 4, overdue: 1 },
      { user_id: "user_002", user_name: "Ahmed Khan", assigned: 5, completed: 4, overdue: 1 },
      { user_id: "user_003", user_name: "Sarah Chen", assigned: 4, completed: 4, overdue: 0 },
      { user_id: "user_004", user_name: "James Wilson", assigned: 3, completed: 3, overdue: 1 },
    ],
    by_source: [
      { source: "Manual", count: 7, color: "#58A6FF" },
      { source: "Audit", count: 4, color: "#3FB950" },
      { source: "CAPA", count: 3, color: "#D29922" },
      { source: "Ticket", count: 3, color: "#BC8CFF" },
    ],
    by_status: [
      { status: "Done", count: 15, color: "#3FB950" },
      { status: "In Progress", count: 1, color: "#58A6FF" },
      { status: "Todo", count: 1, color: "#8B949E" },
    ],
    completion_trend: [
      { date: "W1", completed: 4, created: 4 },
      { date: "W2", completed: 4, created: 5 },
      { date: "W3", completed: 3, created: 4 },
      { date: "W4", completed: 4, created: 4 },
    ],
    overdue_trend: [
      { date: "W1", overdue: 1, on_time: 3 },
      { date: "W2", overdue: 0, on_time: 4 },
      { date: "W3", overdue: 1, on_time: 2 },
      { date: "W4", overdue: 1, on_time: 3 },
    ],
  },
  {
    period: "2026-02",
    total_created: 16,
    total_completed: 14,
    total_overdue: 3,
    avg_completion_days: 3.8,
    velocity: 3.5,
    by_assignee: [
      { user_id: "user_001", user_name: "Maria Silva", assigned: 5, completed: 4, overdue: 1 },
      { user_id: "user_002", user_name: "Ahmed Khan", assigned: 4, completed: 4, overdue: 0 },
      { user_id: "user_003", user_name: "Sarah Chen", assigned: 4, completed: 3, overdue: 1 },
      { user_id: "user_004", user_name: "James Wilson", assigned: 3, completed: 3, overdue: 1 },
    ],
    by_source: [
      { source: "Manual", count: 6, color: "#58A6FF" },
      { source: "Audit", count: 4, color: "#3FB950" },
      { source: "CAPA", count: 3, color: "#D29922" },
      { source: "Ticket", count: 3, color: "#BC8CFF" },
    ],
    by_status: [
      { status: "Done", count: 14, color: "#3FB950" },
      { status: "In Progress", count: 1, color: "#58A6FF" },
      { status: "Todo", count: 1, color: "#8B949E" },
    ],
    completion_trend: [
      { date: "W5", completed: 3, created: 4 },
      { date: "W6", completed: 4, created: 4 },
      { date: "W7", completed: 3, created: 4 },
      { date: "W8", completed: 4, created: 4 },
    ],
    overdue_trend: [
      { date: "W5", overdue: 1, on_time: 2 },
      { date: "W6", overdue: 0, on_time: 4 },
      { date: "W7", overdue: 1, on_time: 2 },
      { date: "W8", overdue: 1, on_time: 3 },
    ],
  },
  {
    period: "2026-03",
    total_created: 19,
    total_completed: 14,
    total_overdue: 5,
    avg_completion_days: 3.5,
    velocity: 4.5,
    by_assignee: [
      { user_id: "user_001", user_name: "Maria Silva", assigned: 6, completed: 5, overdue: 1 },
      { user_id: "user_002", user_name: "Ahmed Khan", assigned: 5, completed: 3, overdue: 2 },
      { user_id: "user_003", user_name: "Sarah Chen", assigned: 5, completed: 4, overdue: 1 },
      { user_id: "user_004", user_name: "James Wilson", assigned: 3, completed: 2, overdue: 1 },
    ],
    by_source: [
      { source: "Manual", count: 7, color: "#58A6FF" },
      { source: "Audit", count: 5, color: "#3FB950" },
      { source: "CAPA", count: 4, color: "#D29922" },
      { source: "Ticket", count: 3, color: "#BC8CFF" },
    ],
    by_status: [
      { status: "Done", count: 14, color: "#3FB950" },
      { status: "In Progress", count: 3, color: "#58A6FF" },
      { status: "Todo", count: 2, color: "#8B949E" },
    ],
    completion_trend: [
      { date: "W9", completed: 4, created: 5 },
      { date: "W10", completed: 5, created: 5 },
      { date: "W11", completed: 5, created: 5 },
      { date: "W12", completed: 4, created: 4 },
    ],
    overdue_trend: [
      { date: "W9", overdue: 1, on_time: 3 },
      { date: "W10", overdue: 2, on_time: 3 },
      { date: "W11", overdue: 1, on_time: 4 },
      { date: "W12", overdue: 1, on_time: 3 },
    ],
  },
];

// ====================================================================
// 9. Custom Dashboards (2 saved)
// ====================================================================

export const customDashboards: CustomDashboard[] = [
  {
    id: "dash_001",
    name: "Executive Overview",
    description: "Default executive dashboard with KPIs, trends, and activity",
    widgets: [
      { id: "w1", type: "kpi_card", title: "Open Tickets", data_source: "tickets", metric: "open_count", position: { x: 0, y: 0 }, size: { w: 1, h: 1 } },
      { id: "w2", type: "kpi_card", title: "Compliance Score", data_source: "audits", metric: "compliance_score", position: { x: 1, y: 0 }, size: { w: 1, h: 1 } },
      { id: "w3", type: "kpi_card", title: "CAPA Overdue", data_source: "capa", metric: "overdue_count", position: { x: 2, y: 0 }, size: { w: 1, h: 1 } },
      { id: "w4", type: "kpi_card", title: "SLA Compliance", data_source: "sla", metric: "compliance_pct", position: { x: 3, y: 0 }, size: { w: 1, h: 1 } },
      { id: "w5", type: "line_chart", title: "Compliance Trend", data_source: "cross_module", metric: "compliance_trend", chart_config: { data_key: "compliance", color: "#3FB950", show_legend: true }, position: { x: 0, y: 1 }, size: { w: 3, h: 2 } },
      { id: "w6", type: "activity_feed", title: "Latest Activity", data_source: "cross_module", position: { x: 3, y: 1 }, size: { w: 1, h: 2 } },
    ],
    owner_id: "user_001",
    shared_with: [],
    created_at: "2026-02-01T10:00:00Z",
    updated_at: "2026-03-10T14:00:00Z",
    is_default: true,
    grid_columns: 4,
  },
  {
    id: "dash_002",
    name: "Operations Focus",
    description: "Detailed operations dashboard for facility managers",
    widgets: [
      { id: "w7", type: "bar_chart", title: "Ticket Volume", data_source: "tickets", metric: "volume", chart_config: { data_key: "created", color: "#58A6FF", show_legend: true }, position: { x: 0, y: 0 }, size: { w: 2, h: 2 } },
      { id: "w8", type: "donut_chart", title: "CAPA by Severity", data_source: "capa", metric: "by_severity", chart_config: { data_key: "count", color: "#F85149" }, position: { x: 2, y: 0 }, size: { w: 2, h: 2 } },
      { id: "w9", type: "line_chart", title: "Resolution Time Trend", data_source: "tickets", metric: "resolution_trend", chart_config: { data_key: "avg_resolution_hours", color: "#D29922", fill: true }, position: { x: 0, y: 2 }, size: { w: 4, h: 2 } },
    ],
    owner_id: "user_001",
    shared_with: ["user_002", "user_003"],
    created_at: "2026-03-01T08:00:00Z",
    updated_at: "2026-03-12T09:00:00Z",
    is_default: false,
    grid_columns: 4,
  },
];

// ====================================================================
// 10. Export Configs (3 presets)
// ====================================================================

export const exportConfigs: ExportConfig[] = [
  {
    id: "exp_001",
    name: "Monthly Executive Report",
    format: "pdf",
    scope: "custom_range",
    date_range: { start: "2026-02-01", end: "2026-02-28" },
    modules: ["tickets", "audits", "capa", "tasks", "sla"],
    include_charts: true,
    include_raw_data: true,
    scheduled: {
      frequency: "monthly",
      recipients: ["ops@acmehotels.com", "gm@acmehotels.com"],
      next_run: "2026-04-01T08:00:00Z",
    },
  },
  {
    id: "exp_002",
    name: "Weekly Ticket Summary",
    format: "csv",
    scope: "custom_range",
    date_range: { start: "2026-03-07", end: "2026-03-14" },
    modules: ["tickets"],
    include_charts: false,
    include_raw_data: true,
    scheduled: {
      frequency: "weekly",
      recipients: ["support@acmehotels.com"],
      next_run: "2026-03-21T08:00:00Z",
    },
  },
  {
    id: "exp_003",
    name: "Ad-hoc Compliance Report",
    format: "pdf",
    scope: "current_view",
    include_charts: true,
    include_raw_data: false,
  },
];

// ====================================================================
// 11. Cross-Module Summary
// ====================================================================

export const crossModuleSummary: CrossModuleSummary = {
  date_range: { start: "2026-02-13", end: "2026-03-14" },
  location_id: null,
  tickets: {
    open: 23,
    resolved_this_period: 42,
    avg_resolution_hours: 4.2,
    sla_compliance_pct: 94,
    trend_vs_prior: 8,
  },
  audits: {
    completed_this_period: 18,
    avg_score: 84,
    pass_rate: 78,
    findings_count: 19,
    trend_vs_prior: -2,
  },
  capa: {
    open: 18,
    overdue: 4,
    closure_rate: 65,
    avg_closure_days: 12,
    trend_vs_prior: 5,
  },
  tasks: {
    open: 12,
    overdue: 5,
    completion_rate: 74,
    velocity: 4.5,
    trend_vs_prior: -3,
  },
  sla: {
    overall_compliance_pct: 94,
    breaches_this_period: 6,
    avg_time_to_breach_hours: 0.75,
    trend_vs_prior: 5,
  },
  overall_health_score: 82,
};

// ====================================================================
// 12. Heatmap data for audit compliance
// ====================================================================

export const auditHeatmapData = [
  { location: "Downtown",  "Oct": 92, "Nov": 88, "Dec": 91, "Jan": 85, "Feb": 90, "Mar": 92 },
  { location: "Airport",   "Oct": 75, "Nov": 72, "Dec": 78, "Jan": 80, "Feb": 76, "Mar": 78 },
  { location: "Resort",    "Oct": 85, "Nov": 87, "Dec": 83, "Jan": 88, "Feb": 86, "Mar": 88 },
  { location: "Marina",    "Oct": 89, "Nov": 85, "Dec": 87, "Jan": 86, "Feb": 88, "Mar": 89 },
  { location: "Uptown",    "Oct": 93, "Nov": 91, "Dec": 90, "Jan": 92, "Feb": 94, "Mar": 93 },
  { location: "Riverside",  "Oct": 90, "Nov": 88, "Dec": 86, "Jan": 89, "Feb": 91, "Mar": 90 },
  { location: "Hillside",  "Oct": 88, "Nov": 86, "Dec": 84, "Jan": 87, "Feb": 85, "Mar": 88 },
  { location: "Beachside", "Oct": 82, "Nov": 79, "Dec": 81, "Jan": 83, "Feb": 80, "Mar": 82 },
  { location: "Harbor",    "Oct": 86, "Nov": 84, "Dec": 85, "Jan": 87, "Feb": 86, "Mar": 86 },
];
