import type {
  Broadcast,
  BroadcastTemplate,
  ReadReceipt,
  LocationReceiptSummary,
  Region,
} from "./types";

export const regions: Region[] = [
  {
    id: "reg_001",
    name: "North America",
    zones: [
      {
        id: "zone_001",
        name: "US West",
        region_id: "reg_001",
        stores: [
          { id: "store_001", name: "Downtown Flagship", zone_id: "zone_001", region_id: "reg_001", staff_count: 82 },
          { id: "store_002", name: "Airport Terminal", zone_id: "zone_001", region_id: "reg_001", staff_count: 64 },
          { id: "store_003", name: "Mall Location", zone_id: "zone_001", region_id: "reg_001", staff_count: 52 },
        ],
      },
      {
        id: "zone_002",
        name: "US East",
        region_id: "reg_001",
        stores: [
          { id: "store_004", name: "Harbor Store", zone_id: "zone_002", region_id: "reg_001", staff_count: 71 },
          { id: "store_005", name: "Campus Hub", zone_id: "zone_002", region_id: "reg_001", staff_count: 68 },
          { id: "store_006", name: "Suburb Center", zone_id: "zone_002", region_id: "reg_001", staff_count: 75 },
        ],
      },
    ],
  },
  {
    id: "reg_002",
    name: "EMEA",
    zones: [
      {
        id: "zone_003",
        name: "UK South",
        region_id: "reg_002",
        stores: [
          { id: "store_007", name: "London Central", zone_id: "zone_003", region_id: "reg_002", staff_count: 55 },
          { id: "store_008", name: "Brighton Pier", zone_id: "zone_003", region_id: "reg_002", staff_count: 48 },
          { id: "store_009", name: "Oxford Street", zone_id: "zone_003", region_id: "reg_002", staff_count: 49 },
        ],
      },
      {
        id: "zone_004",
        name: "UK North",
        region_id: "reg_002",
        stores: [
          { id: "store_010", name: "Manchester Square", zone_id: "zone_004", region_id: "reg_002", staff_count: 46 },
          { id: "store_011", name: "Leeds Central", zone_id: "zone_004", region_id: "reg_002", staff_count: 45 },
          { id: "store_012", name: "Edinburgh Royal", zone_id: "zone_004", region_id: "reg_002", staff_count: 46 },
        ],
      },
    ],
  },
  {
    id: "reg_003",
    name: "Asia Pacific",
    zones: [
      {
        id: "zone_005",
        name: "Japan",
        region_id: "reg_003",
        stores: [
          { id: "store_013", name: "Tokyo Station", zone_id: "zone_005", region_id: "reg_003", staff_count: 58 },
          { id: "store_014", name: "Osaka Central", zone_id: "zone_005", region_id: "reg_003", staff_count: 42 },
        ],
      },
      {
        id: "zone_006",
        name: "Australia",
        region_id: "reg_003",
        stores: [
          { id: "store_015", name: "Sydney Harbour", zone_id: "zone_006", region_id: "reg_003", staff_count: 46 },
        ],
      },
    ],
  },
];

export const broadcasts: Broadcast[] = [
  {
    id: "bc_001",
    title: "Q1 Safety Policy Update",
    body_html: "<h2>Updated Safety Procedures</h2><p>Dear Team,</p><p>Please review the updated safety procedures for Q1 2026. Key changes include:</p><ul><li>Updated fire evacuation routes for Building B</li><li>New PPE requirements for cold storage areas</li><li>Revised chemical handling procedures</li></ul><p>These changes are effective immediately. All staff must complete the updated safety training module by March 31.</p>",
    body_plain: "Updated Safety Procedures. Dear Team, Please review the updated safety procedures for Q1 2026. Key changes include: Updated fire evacuation routes for Building B, New PPE requirements for cold storage areas, Revised chemical handling procedures.",
    status: "sent",
    priority: "urgent",
    audience: { region_ids: ["reg_001", "reg_002", "reg_003"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 847 },
    acknowledgment_required: true,
    template_id: "tmpl_002",
    attachments: [
      { id: "att_001", name: "Q1_Safety_Policy_v3.pdf", type: "pdf", size: "2.4 MB", url: "#" },
      { id: "att_002", name: "evacuation_routes_building_b.png", type: "image", size: "890 KB", url: "#" },
    ],
    created_by: "user_001",
    created_at: "2026-03-12T08:30:00Z",
    updated_at: "2026-03-12T09:00:00Z",
    scheduled_at: null,
    sent_at: "2026-03-12T09:00:00Z",
    stats: { total_recipients: 847, delivered: 839, read: 756, acknowledged: 698, failed: 8, open_rate: 90.1, ack_rate: 82.4 },
    tags: ["safety", "policy", "q1-2026"],
    category: "safety_alert",
  },
  {
    id: "bc_002",
    title: "New Employee Onboarding Process",
    body_html: "<h2>Onboarding Process Update</h2><p>We are pleased to announce a streamlined onboarding process for new hires starting April 1, 2026.</p><p>Key improvements:</p><ul><li>Digital document signing</li><li>Self-paced orientation modules</li><li>Buddy system matching within 24 hours</li></ul>",
    body_plain: "Onboarding Process Update. We are pleased to announce a streamlined onboarding process for new hires starting April 1, 2026.",
    status: "sent",
    priority: "normal",
    audience: { region_ids: ["reg_001", "reg_002", "reg_003"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 847 },
    acknowledgment_required: false,
    template_id: null,
    attachments: [],
    created_by: "user_002",
    created_at: "2026-03-11T14:00:00Z",
    updated_at: "2026-03-11T14:30:00Z",
    scheduled_at: null,
    sent_at: "2026-03-11T14:30:00Z",
    stats: { total_recipients: 847, delivered: 842, read: 631, acknowledged: 0, failed: 5, open_rate: 74.9, ack_rate: 0 },
    tags: ["hr", "onboarding"],
    category: "operational_change",
  },
  {
    id: "bc_003",
    title: "March Maintenance Window Notice",
    body_html: "<h2>Scheduled Maintenance</h2><p>Please be advised that system maintenance will occur on March 22, 2026 from 2:00 AM to 6:00 AM EST.</p><p>During this time, POS systems and inventory management tools will be temporarily unavailable.</p>",
    body_plain: "Scheduled Maintenance. System maintenance on March 22, 2026 from 2:00 AM to 6:00 AM EST. POS and inventory tools temporarily unavailable.",
    status: "sent",
    priority: "normal",
    audience: { region_ids: ["reg_001"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 412 },
    acknowledgment_required: false,
    template_id: null,
    attachments: [],
    created_by: "user_001",
    created_at: "2026-03-10T10:00:00Z",
    updated_at: "2026-03-10T10:15:00Z",
    scheduled_at: null,
    sent_at: "2026-03-10T10:15:00Z",
    stats: { total_recipients: 412, delivered: 410, read: 389, acknowledged: 0, failed: 2, open_rate: 94.9, ack_rate: 0 },
    tags: ["maintenance", "it"],
  },
  {
    id: "bc_004",
    title: "Holiday Operating Hours - Easter 2026",
    body_html: "<h2>Easter Holiday Hours</h2><p>Please note the following adjusted hours for the Easter holiday period:</p><ul><li>Good Friday (Apr 3): Closed</li><li>Saturday (Apr 4): 10am - 4pm</li><li>Easter Sunday (Apr 5): Closed</li><li>Easter Monday (Apr 6): 10am - 6pm</li></ul>",
    body_plain: "Easter Holiday Hours. Good Friday: Closed. Saturday: 10am-4pm. Easter Sunday: Closed. Easter Monday: 10am-6pm.",
    status: "sent",
    priority: "normal",
    audience: { region_ids: ["reg_001", "reg_002"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 701 },
    acknowledgment_required: true,
    template_id: null,
    attachments: [],
    created_by: "user_002",
    created_at: "2026-03-08T11:00:00Z",
    updated_at: "2026-03-08T11:00:00Z",
    scheduled_at: null,
    sent_at: "2026-03-08T11:00:00Z",
    stats: { total_recipients: 701, delivered: 698, read: 672, acknowledged: 645, failed: 3, open_rate: 96.3, ack_rate: 92.0 },
    tags: ["holiday", "hours"],
  },
  {
    id: "bc_005",
    title: "Compliance Training Reminder - GDPR",
    body_html: "<h2>GDPR Training Reminder</h2><p>This is a reminder that all EMEA staff must complete the updated GDPR compliance training by March 31, 2026.</p><p>Access the training module through the Learning Portal. Contact HR with questions.</p>",
    body_plain: "GDPR Training Reminder. All EMEA staff must complete updated GDPR training by March 31, 2026.",
    status: "sent",
    priority: "urgent",
    audience: { region_ids: ["reg_002"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 289 },
    acknowledgment_required: true,
    template_id: "tmpl_006",
    attachments: [{ id: "att_003", name: "GDPR_Training_Guide_2026.pdf", type: "pdf", size: "1.8 MB", url: "#" }],
    created_by: "user_001",
    created_at: "2026-03-07T09:00:00Z",
    updated_at: "2026-03-07T09:00:00Z",
    scheduled_at: null,
    sent_at: "2026-03-07T09:00:00Z",
    stats: { total_recipients: 289, delivered: 287, read: 265, acknowledged: 241, failed: 2, open_rate: 92.3, ack_rate: 83.4 },
    tags: ["compliance", "gdpr", "training"],
    category: "compliance_notice",
  },
  {
    id: "bc_006",
    title: "New Uniform Policy",
    body_html: "<h2>Updated Uniform Standards</h2><p>Effective April 1, 2026, we are introducing updated uniform standards across all locations.</p>",
    body_plain: "Updated Uniform Standards. Effective April 1, 2026, updated uniform standards across all locations.",
    status: "sent",
    priority: "normal",
    audience: { region_ids: ["reg_001", "reg_002", "reg_003"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 847 },
    acknowledgment_required: false,
    template_id: "tmpl_001",
    attachments: [],
    created_by: "user_003",
    created_at: "2026-03-06T15:00:00Z",
    updated_at: "2026-03-06T15:30:00Z",
    scheduled_at: null,
    sent_at: "2026-03-06T15:30:00Z",
    stats: { total_recipients: 847, delivered: 840, read: 712, acknowledged: 0, failed: 7, open_rate: 84.8, ack_rate: 0 },
    tags: ["policy", "uniform"],
    category: "policy_update",
  },
  {
    id: "bc_007",
    title: "Annual Team Building Event",
    body_html: "<h2>2026 Team Building Event</h2><p>We are excited to announce our annual team building event scheduled for May 15-16, 2026.</p><p>This year's theme is 'Building Bridges.' RSVP by April 15.</p>",
    body_plain: "2026 Team Building Event. Annual team building May 15-16, 2026. Theme: Building Bridges. RSVP by April 15.",
    status: "sent",
    priority: "normal",
    audience: { region_ids: ["reg_001"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 412 },
    acknowledgment_required: false,
    template_id: "tmpl_004",
    attachments: [],
    created_by: "user_002",
    created_at: "2026-03-05T12:00:00Z",
    updated_at: "2026-03-05T12:00:00Z",
    scheduled_at: null,
    sent_at: "2026-03-05T12:00:00Z",
    stats: { total_recipients: 412, delivered: 408, read: 356, acknowledged: 0, failed: 4, open_rate: 87.3, ack_rate: 0 },
    tags: ["event", "team-building"],
    category: "event_announcement",
  },
  {
    id: "bc_008",
    title: "Updated POS System Instructions",
    body_html: "<h2>POS System v4.2 Update</h2><p>The POS system has been updated to version 4.2. Please review the key changes and new features.</p>",
    body_plain: "POS System v4.2 Update. Key changes and new features for the updated POS system.",
    status: "sent",
    priority: "normal",
    audience: { region_ids: ["reg_001", "reg_002", "reg_003"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 847 },
    acknowledgment_required: true,
    template_id: null,
    attachments: [{ id: "att_004", name: "POS_v42_Release_Notes.pdf", type: "pdf", size: "1.2 MB", url: "#" }],
    created_by: "user_001",
    created_at: "2026-03-04T16:00:00Z",
    updated_at: "2026-03-04T16:00:00Z",
    scheduled_at: null,
    sent_at: "2026-03-04T16:00:00Z",
    stats: { total_recipients: 847, delivered: 843, read: 798, acknowledged: 721, failed: 4, open_rate: 94.7, ack_rate: 85.1 },
    tags: ["pos", "system-update"],
    category: "operational_change",
  },
  {
    id: "bc_009",
    title: "Cold Weather Safety Procedures",
    body_html: "<h2>Winter Safety Reminder</h2><p>With dropping temperatures, please ensure compliance with cold weather safety protocols.</p>",
    body_plain: "Winter Safety Reminder. Ensure compliance with cold weather safety protocols.",
    status: "sent",
    priority: "critical",
    audience: { region_ids: ["reg_001", "reg_002"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 701 },
    acknowledgment_required: true,
    template_id: "tmpl_002",
    attachments: [],
    created_by: "user_001",
    created_at: "2026-03-03T08:00:00Z",
    updated_at: "2026-03-03T08:00:00Z",
    scheduled_at: null,
    sent_at: "2026-03-03T08:00:00Z",
    stats: { total_recipients: 701, delivered: 697, read: 689, acknowledged: 678, failed: 4, open_rate: 98.9, ack_rate: 96.7 },
    tags: ["safety", "winter"],
    category: "safety_alert",
  },
  {
    id: "bc_010",
    title: "Inventory Count Procedures - Q1",
    body_html: "<h2>Q1 Inventory Count</h2><p>The quarterly inventory count is scheduled for March 28-29. Please review the procedures.</p>",
    body_plain: "Q1 Inventory Count scheduled for March 28-29. Review procedures.",
    status: "sent",
    priority: "normal",
    audience: { region_ids: ["reg_001", "reg_002", "reg_003"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 847 },
    acknowledgment_required: false,
    template_id: null,
    attachments: [],
    created_by: "user_003",
    created_at: "2026-03-02T10:00:00Z",
    updated_at: "2026-03-02T10:00:00Z",
    scheduled_at: null,
    sent_at: "2026-03-02T10:00:00Z",
    stats: { total_recipients: 847, delivered: 841, read: 720, acknowledged: 0, failed: 6, open_rate: 85.6, ack_rate: 0 },
    tags: ["inventory", "q1"],
  },
  {
    id: "bc_011",
    title: "Employee Recognition - February",
    body_html: "<h2>February Star Performers</h2><p>Congratulations to our top performers for February 2026!</p>",
    body_plain: "February Star Performers. Congratulations to our top performers for February 2026!",
    status: "sent",
    priority: "normal",
    audience: { region_ids: ["reg_001", "reg_002", "reg_003"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 847 },
    acknowledgment_required: false,
    template_id: null,
    attachments: [],
    created_by: "user_002",
    created_at: "2026-03-01T09:00:00Z",
    updated_at: "2026-03-01T09:00:00Z",
    scheduled_at: null,
    sent_at: "2026-03-01T09:00:00Z",
    stats: { total_recipients: 847, delivered: 838, read: 654, acknowledged: 0, failed: 9, open_rate: 78.0, ack_rate: 0 },
    tags: ["recognition"],
  },
  {
    id: "bc_012",
    title: "New Food Safety Standards",
    body_html: "<h2>Food Safety Update</h2><p>Updated food safety standards are now in effect for all F&B locations.</p>",
    body_plain: "Updated food safety standards in effect for all F&B locations.",
    status: "sent",
    priority: "urgent",
    audience: { region_ids: ["reg_001", "reg_002"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 701 },
    acknowledgment_required: true,
    template_id: "tmpl_002",
    attachments: [{ id: "att_005", name: "Food_Safety_Standards_2026.pdf", type: "pdf", size: "3.1 MB", url: "#" }],
    created_by: "user_001",
    created_at: "2026-02-28T11:00:00Z",
    updated_at: "2026-02-28T11:00:00Z",
    scheduled_at: null,
    sent_at: "2026-02-28T11:00:00Z",
    stats: { total_recipients: 701, delivered: 696, read: 645, acknowledged: 612, failed: 5, open_rate: 92.7, ack_rate: 87.3 },
    tags: ["food-safety", "compliance"],
    category: "safety_alert",
  },
  {
    id: "bc_013",
    title: "Store Hours Change - Daylight Savings",
    body_html: "<h2>Daylight Savings Time Adjustment</h2><p>Reminder: Clocks spring forward on March 8. Store hours remain the same by local time.</p>",
    body_plain: "Daylight Savings Time Adjustment. Clocks spring forward March 8. Store hours remain same.",
    status: "scheduled",
    priority: "normal",
    audience: { region_ids: ["reg_001"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 412 },
    acknowledgment_required: false,
    template_id: null,
    attachments: [],
    created_by: "user_002",
    created_at: "2026-03-13T10:00:00Z",
    updated_at: "2026-03-13T10:00:00Z",
    scheduled_at: "2026-03-18T09:00:00Z",
    sent_at: null,
    stats: null,
    tags: ["hours", "daylight-savings"],
  },
  {
    id: "bc_014",
    title: "Spring Cleaning Week",
    body_html: "<h2>Spring Cleaning Initiative</h2><p>Our annual spring cleaning week runs March 24-28. All locations must participate.</p>",
    body_plain: "Spring Cleaning Initiative. Annual spring cleaning week March 24-28.",
    status: "scheduled",
    priority: "normal",
    audience: { region_ids: ["reg_001", "reg_002", "reg_003"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 847 },
    acknowledgment_required: false,
    template_id: null,
    attachments: [],
    created_by: "user_003",
    created_at: "2026-03-13T14:00:00Z",
    updated_at: "2026-03-13T14:00:00Z",
    scheduled_at: "2026-03-20T08:00:00Z",
    sent_at: null,
    stats: null,
    tags: ["operations", "cleaning"],
  },
  {
    id: "bc_015",
    title: "APAC Regional Manager Visit",
    body_html: "<h2>Regional Manager Visit</h2><p>APAC regional manager will be visiting all locations during the last week of March.</p>",
    body_plain: "Regional Manager Visit. APAC regional manager visiting all locations last week of March.",
    status: "scheduled",
    priority: "normal",
    audience: { region_ids: ["reg_003"], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 146 },
    acknowledgment_required: false,
    template_id: null,
    attachments: [],
    created_by: "user_001",
    created_at: "2026-03-13T16:00:00Z",
    updated_at: "2026-03-13T16:00:00Z",
    scheduled_at: "2026-03-22T06:00:00Z",
    sent_at: null,
    stats: null,
    tags: ["visit", "apac"],
  },
  {
    id: "bc_016",
    title: "Updated Return Policy Draft",
    body_html: "<h2>Return Policy Changes</h2><p>Draft of updated return policy for review. Please provide feedback.</p>",
    body_plain: "Return Policy Changes. Draft of updated return policy for review.",
    status: "draft",
    priority: "normal",
    audience: { region_ids: [], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 0 },
    acknowledgment_required: false,
    template_id: null,
    attachments: [],
    created_by: "user_002",
    created_at: "2026-03-13T11:00:00Z",
    updated_at: "2026-03-13T11:00:00Z",
    scheduled_at: null,
    sent_at: null,
    stats: null,
    tags: ["policy", "returns"],
    category: "policy_update",
  },
  {
    id: "bc_017",
    title: "Summer Promotion Guidelines",
    body_html: "<h2>Summer 2026 Promotions</h2><p>Initial guidelines for summer promotional activities.</p>",
    body_plain: "Summer 2026 Promotions. Initial guidelines for summer promotional activities.",
    status: "draft",
    priority: "normal",
    audience: { region_ids: [], zone_ids: [], store_ids: [], role_ids: [], total_recipients: 0 },
    acknowledgment_required: false,
    template_id: null,
    attachments: [],
    created_by: "user_003",
    created_at: "2026-03-12T16:00:00Z",
    updated_at: "2026-03-12T16:00:00Z",
    scheduled_at: null,
    sent_at: null,
    stats: null,
    tags: ["promotion", "summer"],
  },
  {
    id: "bc_018",
    title: "Critical: Fire Alarm System Test Failed",
    body_html: "<h2>URGENT: Fire Alarm System Issue</h2><p>The fire alarm test at Airport Terminal has failed. All staff must follow manual evacuation procedures until resolved.</p>",
    body_plain: "URGENT: Fire alarm test failed at Airport Terminal. Follow manual evacuation procedures.",
    status: "failed",
    priority: "critical",
    audience: { region_ids: [], zone_ids: ["zone_001"], store_ids: ["store_002"], role_ids: [], total_recipients: 64 },
    acknowledgment_required: true,
    template_id: null,
    attachments: [],
    created_by: "user_001",
    created_at: "2026-03-13T17:00:00Z",
    updated_at: "2026-03-13T17:05:00Z",
    scheduled_at: null,
    sent_at: null,
    stats: null,
    tags: ["fire-safety", "critical"],
    category: "safety_alert",
  },
];

export const broadcastTemplates: BroadcastTemplate[] = [
  {
    id: "tmpl_001",
    name: "Policy Update Announcement",
    description: "Standard template for communicating policy changes and updates to all staff.",
    category: "policy_update",
    body_html: "<h2>[Policy Name] Update</h2><p>Dear Team,</p><p>We are writing to inform you about an important update to our [Policy Area] policy. Effective [Date], the following changes will be in place:</p><ul><li>[Change 1]</li><li>[Change 2]</li><li>[Change 3]</li></ul><p>Please review the attached documentation for full details. If you have any questions, contact your direct supervisor or the HR department.</p><p>Thank you for your attention to this matter.</p>",
    body_preview: "Standard template for communicating policy changes and updates to all staff.",
    thumbnail_color: "#6366F1",
    tags: ["policy", "hr"],
    usage_count: 24,
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2026-02-01T10:00:00Z",
    is_system: true,
    acknowledgment_default: true,
    priority_default: "normal",
  },
  {
    id: "tmpl_002",
    name: "Safety Alert",
    description: "High-priority template for safety-related announcements requiring immediate attention.",
    category: "safety_alert",
    body_html: "<h2>Safety Alert: [Title]</h2><p><strong>Attention all staff,</strong></p><p>This is an important safety notification regarding [subject]. Please read carefully and take the following actions:</p><ol><li>[Action 1]</li><li>[Action 2]</li><li>[Action 3]</li></ol><p><strong>Effective immediately.</strong> Failure to comply may result in disciplinary action.</p><p>For questions, contact the Safety Team at safety@company.com.</p>",
    body_preview: "High-priority template for safety-related announcements requiring immediate attention.",
    thumbnail_color: "#EF4444",
    tags: ["safety", "urgent"],
    usage_count: 18,
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2026-01-20T10:00:00Z",
    is_system: true,
    acknowledgment_default: true,
    priority_default: "urgent",
  },
  {
    id: "tmpl_003",
    name: "Operational Change Notice",
    description: "Inform staff about changes to daily operations, processes, or systems.",
    category: "operational_change",
    body_html: "<h2>Operational Update: [Title]</h2><p>Dear Team,</p><p>Starting [Date], we will be implementing the following changes to our operations:</p><p><strong>What is changing:</strong></p><ul><li>[Detail 1]</li><li>[Detail 2]</li></ul><p><strong>What you need to do:</strong></p><ul><li>[Action 1]</li><li>[Action 2]</li></ul><p>Training resources are available in the Learning Portal.</p>",
    body_preview: "Inform staff about changes to daily operations, processes, or systems.",
    thumbnail_color: "#F59E0B",
    tags: ["operations", "process"],
    usage_count: 31,
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2026-02-15T10:00:00Z",
    is_system: true,
    acknowledgment_default: false,
    priority_default: "normal",
  },
  {
    id: "tmpl_004",
    name: "Event Announcement",
    description: "Template for announcing company events, team activities, and social gatherings.",
    category: "event_announcement",
    body_html: "<h2>[Event Name]</h2><p>We are excited to announce [event description]!</p><p><strong>Details:</strong></p><ul><li>Date: [Date]</li><li>Time: [Time]</li><li>Location: [Location]</li></ul><p>Please RSVP by [RSVP Date]. We look forward to seeing you there!</p>",
    body_preview: "Template for announcing company events, team activities, and social gatherings.",
    thumbnail_color: "#10B981",
    tags: ["event", "social"],
    usage_count: 15,
    created_at: "2025-02-01T10:00:00Z",
    updated_at: "2025-12-01T10:00:00Z",
    is_system: true,
    acknowledgment_default: false,
    priority_default: "normal",
  },
  {
    id: "tmpl_005",
    name: "Training Reminder",
    description: "Reminder template for mandatory training deadlines and learning opportunities.",
    category: "training_reminder",
    body_html: "<h2>Training Reminder: [Course Name]</h2><p>This is a reminder that [training name] must be completed by <strong>[Deadline]</strong>.</p><p><strong>Who needs to complete this:</strong> [Target audience]</p><p><strong>How to access:</strong> Log into the Learning Portal and navigate to [path].</p><p>If you have already completed this training, please disregard this message.</p>",
    body_preview: "Reminder template for mandatory training deadlines and learning opportunities.",
    thumbnail_color: "#8B5CF6",
    tags: ["training", "reminder"],
    usage_count: 22,
    created_at: "2025-03-01T10:00:00Z",
    updated_at: "2026-01-15T10:00:00Z",
    is_system: true,
    acknowledgment_default: false,
    priority_default: "normal",
  },
  {
    id: "tmpl_006",
    name: "Compliance Notice",
    description: "Official compliance communication requiring staff acknowledgment and action.",
    category: "compliance_notice",
    body_html: "<h2>Compliance Notice: [Subject]</h2><p><strong>All staff are required to read and acknowledge this notice.</strong></p><p>[Compliance requirement details]</p><p><strong>Key requirements:</strong></p><ol><li>[Requirement 1]</li><li>[Requirement 2]</li><li>[Requirement 3]</li></ol><p><strong>Deadline:</strong> [Date]</p><p>Non-compliance may result in regulatory penalties. Contact the Compliance Team with questions.</p>",
    body_preview: "Official compliance communication requiring staff acknowledgment and action.",
    thumbnail_color: "#EC4899",
    tags: ["compliance", "legal"],
    usage_count: 12,
    created_at: "2025-04-01T10:00:00Z",
    updated_at: "2026-02-01T10:00:00Z",
    is_system: true,
    acknowledgment_default: true,
    priority_default: "urgent",
  },
  {
    id: "tmpl_007",
    name: "General Announcement",
    description: "Multi-purpose template for general staff communications and updates.",
    category: "general",
    body_html: "<h2>[Announcement Title]</h2><p>Dear Team,</p><p>[Your message here]</p><p>If you have any questions, please reach out to [contact].</p><p>Best regards,<br/>[Your Name]</p>",
    body_preview: "Multi-purpose template for general staff communications and updates.",
    thumbnail_color: "#64748B",
    tags: ["general"],
    usage_count: 45,
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2026-03-01T10:00:00Z",
    is_system: true,
    acknowledgment_default: false,
    priority_default: "normal",
  },
  {
    id: "tmpl_008",
    name: "Weekly Store Update",
    description: "Custom template for weekly store performance summaries and action items.",
    category: "operational_change",
    body_html: "<h2>Weekly Update - [Week]</h2><p><strong>Performance Highlights:</strong></p><ul><li>[Highlight 1]</li><li>[Highlight 2]</li></ul><p><strong>This Week's Focus Areas:</strong></p><ul><li>[Focus 1]</li><li>[Focus 2]</li></ul><p><strong>Action Items:</strong></p><ul><li>[Action 1]</li><li>[Action 2]</li></ul>",
    body_preview: "Custom template for weekly store performance summaries and action items.",
    thumbnail_color: "#0EA5E9",
    tags: ["weekly", "performance"],
    usage_count: 38,
    created_at: "2025-06-15T10:00:00Z",
    updated_at: "2026-03-10T10:00:00Z",
    is_system: false,
    acknowledgment_default: false,
    priority_default: "normal",
  },
  {
    id: "tmpl_009",
    name: "Emergency Contact Update",
    description: "Request staff to verify or update their emergency contact information.",
    category: "compliance_notice",
    body_html: "<h2>Emergency Contact Verification</h2><p>It is time for our annual emergency contact verification. Please log into the HR portal and confirm your emergency contact details are up to date.</p><p><strong>Deadline:</strong> [Date]</p><p>This is a mandatory compliance requirement.</p>",
    body_preview: "Request staff to verify or update their emergency contact information.",
    thumbnail_color: "#F97316",
    tags: ["hr", "emergency", "compliance"],
    usage_count: 8,
    created_at: "2025-09-01T10:00:00Z",
    updated_at: "2026-02-20T10:00:00Z",
    is_system: false,
    acknowledgment_default: true,
    priority_default: "normal",
  },
  {
    id: "tmpl_010",
    name: "Seasonal Menu Launch",
    description: "Announcement template for new seasonal menu items and pricing updates.",
    category: "operational_change",
    body_html: "<h2>[Season] Menu Launch</h2><p>We are excited to introduce our new [season] menu, effective [Date]!</p><p><strong>New items:</strong></p><ul><li>[Item 1] - $[Price]</li><li>[Item 2] - $[Price]</li><li>[Item 3] - $[Price]</li></ul><p>Training for new menu items is available in the Learning Portal. All F&B staff must complete training before launch day.</p>",
    body_preview: "Announcement template for new seasonal menu items and pricing updates.",
    thumbnail_color: "#14B8A6",
    tags: ["menu", "f&b", "seasonal"],
    usage_count: 6,
    created_at: "2025-11-01T10:00:00Z",
    updated_at: "2026-03-05T10:00:00Z",
    is_system: false,
    acknowledgment_default: false,
    priority_default: "normal",
  },
];

// Read receipts for broadcast bc_001 (Q1 Safety Policy Update)
export const readReceipts: ReadReceipt[] = [
  // Downtown Flagship - store_001
  { id: "rr_001", broadcast_id: "bc_001", user_id: "u_101", user_name: "James Wilson", user_role: "Store Manager", location_id: "store_001", location_name: "Downtown Flagship", region_id: "reg_001", region_name: "North America", status: "acknowledged", delivered_at: "2026-03-12T09:01:00Z", read_at: "2026-03-12T09:05:00Z", acknowledged_at: "2026-03-12T09:10:00Z" },
  { id: "rr_002", broadcast_id: "bc_001", user_id: "u_102", user_name: "Sarah Chen", user_role: "Shift Supervisor", location_id: "store_001", location_name: "Downtown Flagship", region_id: "reg_001", region_name: "North America", status: "acknowledged", delivered_at: "2026-03-12T09:01:00Z", read_at: "2026-03-12T09:15:00Z", acknowledged_at: "2026-03-12T09:20:00Z" },
  { id: "rr_003", broadcast_id: "bc_001", user_id: "u_103", user_name: "Tom Baker", user_role: "Field Staff", location_id: "store_001", location_name: "Downtown Flagship", region_id: "reg_001", region_name: "North America", status: "read", delivered_at: "2026-03-12T09:02:00Z", read_at: "2026-03-12T10:30:00Z", acknowledged_at: null },
  { id: "rr_004", broadcast_id: "bc_001", user_id: "u_104", user_name: "Aisha Patel", user_role: "Field Staff", location_id: "store_001", location_name: "Downtown Flagship", region_id: "reg_001", region_name: "North America", status: "delivered", delivered_at: "2026-03-12T09:01:00Z", read_at: null, acknowledged_at: null },
  { id: "rr_005", broadcast_id: "bc_001", user_id: "u_105", user_name: "Michael Ross", user_role: "Back Office", location_id: "store_001", location_name: "Downtown Flagship", region_id: "reg_001", region_name: "North America", status: "acknowledged", delivered_at: "2026-03-12T09:01:00Z", read_at: "2026-03-12T09:08:00Z", acknowledged_at: "2026-03-12T09:12:00Z" },
  // Airport Terminal - store_002
  { id: "rr_006", broadcast_id: "bc_001", user_id: "u_106", user_name: "Linda Tran", user_role: "Store Manager", location_id: "store_002", location_name: "Airport Terminal", region_id: "reg_001", region_name: "North America", status: "acknowledged", delivered_at: "2026-03-12T09:01:00Z", read_at: "2026-03-12T09:03:00Z", acknowledged_at: "2026-03-12T09:05:00Z" },
  { id: "rr_007", broadcast_id: "bc_001", user_id: "u_107", user_name: "David Kim", user_role: "Shift Supervisor", location_id: "store_002", location_name: "Airport Terminal", region_id: "reg_001", region_name: "North America", status: "read", delivered_at: "2026-03-12T09:02:00Z", read_at: "2026-03-12T11:00:00Z", acknowledged_at: null },
  { id: "rr_008", broadcast_id: "bc_001", user_id: "u_108", user_name: "Elena Rodriguez", user_role: "Field Staff", location_id: "store_002", location_name: "Airport Terminal", region_id: "reg_001", region_name: "North America", status: "undelivered", delivered_at: null, read_at: null, acknowledged_at: null },
  // London Central - store_007
  { id: "rr_009", broadcast_id: "bc_001", user_id: "u_109", user_name: "Oliver Hughes", user_role: "Store Manager", location_id: "store_007", location_name: "London Central", region_id: "reg_002", region_name: "EMEA", status: "acknowledged", delivered_at: "2026-03-12T09:01:00Z", read_at: "2026-03-12T09:10:00Z", acknowledged_at: "2026-03-12T09:15:00Z" },
  { id: "rr_010", broadcast_id: "bc_001", user_id: "u_110", user_name: "Charlotte Webb", user_role: "Shift Supervisor", location_id: "store_007", location_name: "London Central", region_id: "reg_002", region_name: "EMEA", status: "acknowledged", delivered_at: "2026-03-12T09:01:00Z", read_at: "2026-03-12T09:20:00Z", acknowledged_at: "2026-03-12T09:25:00Z" },
  { id: "rr_011", broadcast_id: "bc_001", user_id: "u_111", user_name: "Harry Davies", user_role: "Field Staff", location_id: "store_007", location_name: "London Central", region_id: "reg_002", region_name: "EMEA", status: "read", delivered_at: "2026-03-12T09:02:00Z", read_at: "2026-03-12T14:00:00Z", acknowledged_at: null },
  // Edinburgh Royal - store_012
  { id: "rr_012", broadcast_id: "bc_001", user_id: "u_112", user_name: "Fiona MacLeod", user_role: "Store Manager", location_id: "store_012", location_name: "Edinburgh Royal", region_id: "reg_002", region_name: "EMEA", status: "acknowledged", delivered_at: "2026-03-12T09:01:00Z", read_at: "2026-03-12T09:30:00Z", acknowledged_at: "2026-03-12T09:35:00Z" },
  { id: "rr_013", broadcast_id: "bc_001", user_id: "u_113", user_name: "Angus Campbell", user_role: "Shift Supervisor", location_id: "store_012", location_name: "Edinburgh Royal", region_id: "reg_002", region_name: "EMEA", status: "delivered", delivered_at: "2026-03-12T09:02:00Z", read_at: null, acknowledged_at: null },
  { id: "rr_014", broadcast_id: "bc_001", user_id: "u_114", user_name: "Isla Murray", user_role: "Field Staff", location_id: "store_012", location_name: "Edinburgh Royal", region_id: "reg_002", region_name: "EMEA", status: "read", delivered_at: "2026-03-12T09:01:00Z", read_at: "2026-03-12T16:00:00Z", acknowledged_at: null },
  { id: "rr_015", broadcast_id: "bc_001", user_id: "u_115", user_name: "Craig Stewart", user_role: "Back Office", location_id: "store_012", location_name: "Edinburgh Royal", region_id: "reg_002", region_name: "EMEA", status: "undelivered", delivered_at: null, read_at: null, acknowledged_at: null },
  // Tokyo Station - store_013
  { id: "rr_016", broadcast_id: "bc_001", user_id: "u_116", user_name: "Yuki Tanaka", user_role: "Store Manager", location_id: "store_013", location_name: "Tokyo Station", region_id: "reg_003", region_name: "Asia Pacific", status: "acknowledged", delivered_at: "2026-03-12T09:01:00Z", read_at: "2026-03-12T09:05:00Z", acknowledged_at: "2026-03-12T09:08:00Z" },
  { id: "rr_017", broadcast_id: "bc_001", user_id: "u_117", user_name: "Kenji Sato", user_role: "Shift Supervisor", location_id: "store_013", location_name: "Tokyo Station", region_id: "reg_003", region_name: "Asia Pacific", status: "acknowledged", delivered_at: "2026-03-12T09:01:00Z", read_at: "2026-03-12T09:10:00Z", acknowledged_at: "2026-03-12T09:15:00Z" },
  { id: "rr_018", broadcast_id: "bc_001", user_id: "u_118", user_name: "Mai Yoshida", user_role: "Field Staff", location_id: "store_013", location_name: "Tokyo Station", region_id: "reg_003", region_name: "Asia Pacific", status: "read", delivered_at: "2026-03-12T09:02:00Z", read_at: "2026-03-12T12:00:00Z", acknowledged_at: null },
];

export const locationReceiptSummaries: LocationReceiptSummary[] = [
  { location_id: "store_001", location_name: "Downtown Flagship", region_id: "reg_001", region_name: "North America", zone_id: "zone_001", zone_name: "US West", total_staff: 82, delivered: 82, read: 78, acknowledged: 76, compliance_pct: 92.7 },
  { location_id: "store_002", location_name: "Airport Terminal", region_id: "reg_001", region_name: "North America", zone_id: "zone_001", zone_name: "US West", total_staff: 64, delivered: 62, read: 55, acknowledged: 48, compliance_pct: 75.0 },
  { location_id: "store_003", location_name: "Mall Location", region_id: "reg_001", region_name: "North America", zone_id: "zone_001", zone_name: "US West", total_staff: 52, delivered: 52, read: 49, acknowledged: 46, compliance_pct: 88.5 },
  { location_id: "store_004", location_name: "Harbor Store", region_id: "reg_001", region_name: "North America", zone_id: "zone_002", zone_name: "US East", total_staff: 71, delivered: 70, read: 65, acknowledged: 61, compliance_pct: 85.9 },
  { location_id: "store_005", location_name: "Campus Hub", region_id: "reg_001", region_name: "North America", zone_id: "zone_002", zone_name: "US East", total_staff: 68, delivered: 68, read: 64, acknowledged: 62, compliance_pct: 91.2 },
  { location_id: "store_006", location_name: "Suburb Center", region_id: "reg_001", region_name: "North America", zone_id: "zone_002", zone_name: "US East", total_staff: 75, delivered: 74, read: 70, acknowledged: 68, compliance_pct: 90.7 },
  { location_id: "store_007", location_name: "London Central", region_id: "reg_002", region_name: "EMEA", zone_id: "zone_003", zone_name: "UK South", total_staff: 55, delivered: 55, read: 51, acknowledged: 48, compliance_pct: 87.3 },
  { location_id: "store_008", location_name: "Brighton Pier", region_id: "reg_002", region_name: "EMEA", zone_id: "zone_003", zone_name: "UK South", total_staff: 48, delivered: 48, read: 41, acknowledged: 35, compliance_pct: 72.9 },
  { location_id: "store_009", location_name: "Oxford Street", region_id: "reg_002", region_name: "EMEA", zone_id: "zone_003", zone_name: "UK South", total_staff: 49, delivered: 49, read: 45, acknowledged: 42, compliance_pct: 85.7 },
  { location_id: "store_010", location_name: "Manchester Square", region_id: "reg_002", region_name: "EMEA", zone_id: "zone_004", zone_name: "UK North", total_staff: 46, delivered: 46, read: 42, acknowledged: 39, compliance_pct: 84.8 },
  { location_id: "store_011", location_name: "Leeds Central", region_id: "reg_002", region_name: "EMEA", zone_id: "zone_004", zone_name: "UK North", total_staff: 45, delivered: 44, read: 38, acknowledged: 34, compliance_pct: 75.6 },
  { location_id: "store_012", location_name: "Edinburgh Royal", region_id: "reg_002", region_name: "EMEA", zone_id: "zone_004", zone_name: "UK North", total_staff: 46, delivered: 45, read: 38, acknowledged: 29, compliance_pct: 63.0 },
  { location_id: "store_013", location_name: "Tokyo Station", region_id: "reg_003", region_name: "Asia Pacific", zone_id: "zone_005", zone_name: "Japan", total_staff: 58, delivered: 58, read: 56, acknowledged: 54, compliance_pct: 93.1 },
  { location_id: "store_014", location_name: "Osaka Central", region_id: "reg_003", region_name: "Asia Pacific", zone_id: "zone_005", zone_name: "Japan", total_staff: 42, delivered: 42, read: 40, acknowledged: 38, compliance_pct: 90.5 },
  { location_id: "store_015", location_name: "Sydney Harbour", region_id: "reg_003", region_name: "Asia Pacific", zone_id: "zone_006", zone_name: "Australia", total_staff: 46, delivered: 44, read: 24, acknowledged: 18, compliance_pct: 39.1 },
];
