import type {
  KBCategory,
  KBCollection,
  KBArticle,
  ArticleAnalytics,
  KBSearchGap,
} from "./types";

// ---------- 8 Categories (5 top-level, 3 children) ----------

export const kbCategories: KBCategory[] = [
  {
    id: "kbcat_001",
    name: "Food Safety",
    slug: "food-safety",
    description: "Food handling, storage, and safety compliance guidelines",
    icon: "ShieldCheck",
    color: "#3FB950",
    article_count: 7,
    parent_id: null,
    sort_order: 1,
    created_at: "2026-01-10T09:00:00Z",
    updated_at: "2026-03-01T10:00:00Z",
  },
  {
    id: "kbcat_002",
    name: "Equipment & Maintenance",
    slug: "equipment-maintenance",
    description: "Equipment operation, maintenance schedules, and troubleshooting",
    icon: "Wrench",
    color: "#58A6FF",
    article_count: 6,
    parent_id: null,
    sort_order: 2,
    created_at: "2026-01-10T09:00:00Z",
    updated_at: "2026-03-05T14:00:00Z",
  },
  {
    id: "kbcat_003",
    name: "Refrigeration",
    slug: "refrigeration",
    description: "Refrigeration equipment monitoring and maintenance",
    icon: "Snowflake",
    color: "#79C0FF",
    article_count: 3,
    parent_id: "kbcat_002",
    sort_order: 1,
    created_at: "2026-01-15T09:00:00Z",
    updated_at: "2026-03-02T11:00:00Z",
  },
  {
    id: "kbcat_004",
    name: "Training & Onboarding",
    slug: "training-onboarding",
    description: "Staff training materials, onboarding guides, and certification tracking",
    icon: "GraduationCap",
    color: "#D2A8FF",
    article_count: 4,
    parent_id: null,
    sort_order: 3,
    created_at: "2026-01-12T09:00:00Z",
    updated_at: "2026-02-28T09:00:00Z",
  },
  {
    id: "kbcat_005",
    name: "Compliance & Audits",
    slug: "compliance-audits",
    description: "Regulatory compliance procedures and audit preparation",
    icon: "ClipboardCheck",
    color: "#FFA657",
    article_count: 3,
    parent_id: null,
    sort_order: 4,
    created_at: "2026-01-14T09:00:00Z",
    updated_at: "2026-03-08T09:00:00Z",
  },
  {
    id: "kbcat_006",
    name: "Operations",
    slug: "operations",
    description: "Daily operations, opening/closing procedures, and workflows",
    icon: "Settings",
    color: "#F778BA",
    article_count: 2,
    parent_id: null,
    sort_order: 5,
    created_at: "2026-01-16T09:00:00Z",
    updated_at: "2026-03-10T09:00:00Z",
  },
  {
    id: "kbcat_007",
    name: "HVAC Systems",
    slug: "hvac-systems",
    description: "HVAC system operations and maintenance",
    icon: "Wind",
    color: "#7EE787",
    article_count: 2,
    parent_id: "kbcat_002",
    sort_order: 2,
    created_at: "2026-01-18T09:00:00Z",
    updated_at: "2026-02-20T09:00:00Z",
  },
  {
    id: "kbcat_008",
    name: "Food Storage",
    slug: "food-storage",
    description: "Proper food storage techniques and requirements",
    icon: "Package",
    color: "#56D364",
    article_count: 3,
    parent_id: "kbcat_001",
    sort_order: 1,
    created_at: "2026-01-20T09:00:00Z",
    updated_at: "2026-03-04T09:00:00Z",
  },
];

// ---------- 3 Collections (1 featured) ----------

export const kbCollections: KBCollection[] = [
  {
    id: "kbcol_001",
    name: "Getting Started",
    description: "Essential guides for new team members to get up and running quickly",
    article_ids: ["kba_001", "kba_004", "kba_010", "kba_015"],
    is_featured: true,
    sort_order: 1,
    created_at: "2026-01-20T09:00:00Z",
  },
  {
    id: "kbcol_002",
    name: "Safety Essentials",
    description: "Critical safety procedures every staff member must know",
    article_ids: ["kba_002", "kba_003", "kba_006", "kba_009"],
    is_featured: false,
    sort_order: 2,
    created_at: "2026-02-01T09:00:00Z",
  },
  {
    id: "kbcol_003",
    name: "Monthly Maintenance Guides",
    description: "Step-by-step maintenance procedures organized by frequency",
    article_ids: ["kba_005", "kba_007", "kba_011", "kba_016"],
    is_featured: false,
    sort_order: 3,
    created_at: "2026-02-10T09:00:00Z",
  },
];

// ---------- 25 Articles ----------

export const kbArticles: KBArticle[] = [
  {
    id: "kba_001",
    title: "Food Safety & Handling Fundamentals",
    slug: "food-safety-handling-fundamentals",
    excerpt: "A comprehensive guide to food safety principles, proper handling techniques, and hygiene standards for all kitchen and service staff.",
    body_html: `<h2 id="overview">Overview</h2><p>Food safety is the cornerstone of our operations. Every team member must understand and follow these fundamental guidelines to protect our customers and maintain regulatory compliance.</p><h2 id="temperature-danger-zone">Temperature Danger Zone</h2><p>The temperature danger zone is between 4&deg;C (40&deg;F) and 60&deg;C (140&deg;F). Bacteria multiply rapidly in this range, so food must not remain in this zone for more than 2 hours.</p><h3 id="cold-food-storage">Cold Food Storage</h3><p>All refrigerated items must be stored at or below 4&deg;C. Use calibrated thermometers to check temperatures at least twice daily. Record readings in the temperature log.</p><h3 id="hot-food-holding">Hot Food Holding</h3><p>Hot foods must be held at 60&deg;C or above. Use warming trays and heat lamps to maintain temperatures. Check and record temperatures every 30 minutes during service.</p><h2 id="hand-hygiene">Hand Hygiene</h2><p>Proper hand washing is required before handling food, after using the restroom, after touching raw meat, and after any contamination risk. Wash hands with warm water and soap for at least 20 seconds.</p><h2 id="cross-contamination">Preventing Cross-Contamination</h2><p>Use separate cutting boards for raw meats and ready-to-eat foods. Color-coded equipment helps prevent mix-ups:</p><ul><li>Red boards: raw meat</li><li>Green boards: vegetables</li><li>Blue boards: seafood</li><li>White boards: dairy and ready-to-eat</li></ul><h2 id="personal-hygiene">Personal Hygiene Requirements</h2><p>All staff must wear clean uniforms, hair nets or caps, and remove jewelry before entering food preparation areas. Report any illness symptoms to your supervisor immediately.</p>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_001",
    collection_ids: ["kbcol_001", "kbcol_002"],
    tags: ["food-safety", "hygiene", "training", "fundamentals"],
    author_id: "usr_001",
    last_edited_by: "usr_001",
    sop_source_id: "sop_001",
    sop_source_name: "Food Safety & Handling Procedure",
    featured_image: null,
    table_of_contents: [
      { id: "overview", text: "Overview", level: 2 },
      { id: "temperature-danger-zone", text: "Temperature Danger Zone", level: 2 },
      { id: "cold-food-storage", text: "Cold Food Storage", level: 3 },
      { id: "hot-food-holding", text: "Hot Food Holding", level: 3 },
      { id: "hand-hygiene", text: "Hand Hygiene", level: 2 },
      { id: "cross-contamination", text: "Preventing Cross-Contamination", level: 2 },
      { id: "personal-hygiene", text: "Personal Hygiene Requirements", level: 2 },
    ],
    created_at: "2026-01-20T10:00:00Z",
    updated_at: "2026-03-10T15:00:00Z",
    published_at: "2026-01-22T09:00:00Z",
    views_count: 456,
    helpful_count: 398,
    not_helpful_count: 42,
  },
  {
    id: "kba_002",
    title: "Refrigeration Equipment Monitoring Guide",
    slug: "refrigeration-equipment-monitoring",
    excerpt: "Standard procedures for monitoring refrigeration equipment temperatures, recording readings, and responding to temperature deviations.",
    body_html: `<h2 id="purpose">Purpose</h2><p>This guide establishes the procedures for monitoring all refrigeration equipment across our locations. Proper temperature monitoring prevents food spoilage and ensures compliance with health regulations.</p><h2 id="equipment-list">Equipment Covered</h2><p>This guide covers walk-in coolers, reach-in refrigerators, freezers, blast chillers, and cold prep tables. Each unit must have a calibrated digital thermometer.</p><h2 id="monitoring-schedule">Monitoring Schedule</h2><p>Temperature checks must be performed:</p><ul><li>At opening (before food prep begins)</li><li>Mid-shift (between 11:00 and 13:00)</li><li>At closing (after all food is stored)</li></ul><h3 id="recording-procedure">Recording Procedure</h3><p>Use the digital temperature log system. Each reading must include the unit ID, temperature, time, and the initials of the person taking the reading.</p><h2 id="corrective-actions">Corrective Actions</h2><p>If a temperature reading is out of range, follow these steps immediately:</p><ol><li>Check if the unit door has been left open</li><li>Verify the thermostat setting</li><li>Check for ice buildup on coils</li><li>If temperature is above 7&deg;C for a cooler, notify the shift manager</li><li>Document the corrective action taken</li></ol><h2 id="troubleshooting">Troubleshooting Common Issues</h2><p>Common causes of temperature deviations include overloading the unit, blocked air vents, worn door gaskets, and compressor issues. Refer to the equipment maintenance schedule for preventive measures.</p>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_003",
    collection_ids: ["kbcol_002", "kbcol_003"],
    tags: ["refrigeration", "temperature", "monitoring", "equipment"],
    author_id: "usr_002",
    last_edited_by: "usr_001",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "purpose", text: "Purpose", level: 2 },
      { id: "equipment-list", text: "Equipment Covered", level: 2 },
      { id: "monitoring-schedule", text: "Monitoring Schedule", level: 2 },
      { id: "recording-procedure", text: "Recording Procedure", level: 3 },
      { id: "corrective-actions", text: "Corrective Actions", level: 2 },
      { id: "troubleshooting", text: "Troubleshooting Common Issues", level: 2 },
    ],
    created_at: "2026-01-25T10:00:00Z",
    updated_at: "2026-03-08T14:00:00Z",
    published_at: "2026-01-26T09:00:00Z",
    views_count: 389,
    helpful_count: 342,
    not_helpful_count: 47,
  },
  {
    id: "kba_003",
    title: "Temperature Monitoring & Recording Standards",
    slug: "temperature-monitoring-recording-standards",
    excerpt: "Detailed standards for temperature monitoring across all food storage and preparation areas, including corrective action procedures.",
    body_html: `<h2 id="scope">Scope</h2><p>This article covers temperature monitoring standards for all locations. It applies to coolers, freezers, hot holding units, and prep stations.</p><h2 id="frequency">Monitoring Frequency</h2><p>All temperature-sensitive units must be checked a minimum of three times per day. Critical units (walk-in coolers, main freezer) require checks every four hours.</p><h2 id="acceptable-ranges">Acceptable Temperature Ranges</h2><ul><li>Walk-in coolers: 0&deg;C to 4&deg;C (32&deg;F to 40&deg;F)</li><li>Freezers: -18&deg;C or below (0&deg;F or below)</li><li>Hot holding: 60&deg;C or above (140&deg;F or above)</li><li>Prep surfaces: below 4&deg;C during active use</li></ul><h2 id="documentation">Documentation Requirements</h2><p>All readings must be logged digitally within 15 minutes of the check. Include unit ID, temperature, time, and operator initials.</p>`,
    status: "published",
    visibility: "public",
    category_id: "kbcat_001",
    collection_ids: ["kbcol_002"],
    tags: ["temperature", "monitoring", "compliance", "standards"],
    author_id: "usr_003",
    last_edited_by: "usr_003",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "scope", text: "Scope", level: 2 },
      { id: "frequency", text: "Monitoring Frequency", level: 2 },
      { id: "acceptable-ranges", text: "Acceptable Temperature Ranges", level: 2 },
      { id: "documentation", text: "Documentation Requirements", level: 2 },
    ],
    created_at: "2026-02-01T10:00:00Z",
    updated_at: "2026-03-05T11:00:00Z",
    published_at: "2026-02-02T09:00:00Z",
    views_count: 312,
    helpful_count: 284,
    not_helpful_count: 28,
  },
  {
    id: "kba_004",
    title: "New Employee Onboarding Guide",
    slug: "new-employee-onboarding",
    excerpt: "Complete onboarding guide for new team members covering first-day orientation, required certifications, and initial training modules.",
    body_html: `<h2 id="welcome">Welcome to the Team</h2><p>Congratulations on joining our team! This guide will walk you through everything you need to know during your first week.</p><h2 id="first-day">First Day Checklist</h2><ul><li>Report to your location manager for orientation</li><li>Complete HR paperwork and I-9 verification</li><li>Receive your employee badge and uniform</li><li>Tour the facility with your assigned mentor</li><li>Review safety protocols and emergency procedures</li></ul><h2 id="required-training">Required Training Modules</h2><p>Within your first two weeks, you must complete the following training modules:</p><ol><li>Food Safety Fundamentals (4 hours)</li><li>Workplace Safety (2 hours)</li><li>Customer Service Excellence (3 hours)</li><li>Equipment Operation Basics (2 hours)</li><li>Company Policies & Procedures (1 hour)</li></ol><h2 id="certifications">Required Certifications</h2><p>Depending on your role, you may need to obtain food handler certification within 30 days of hire. Your manager will provide details on the certification process.</p>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_004",
    collection_ids: ["kbcol_001"],
    tags: ["onboarding", "new-hire", "training", "orientation"],
    author_id: "usr_001",
    last_edited_by: "usr_002",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "welcome", text: "Welcome to the Team", level: 2 },
      { id: "first-day", text: "First Day Checklist", level: 2 },
      { id: "required-training", text: "Required Training Modules", level: 2 },
      { id: "certifications", text: "Required Certifications", level: 2 },
    ],
    created_at: "2026-02-05T10:00:00Z",
    updated_at: "2026-03-01T09:00:00Z",
    published_at: "2026-02-06T09:00:00Z",
    views_count: 234,
    helpful_count: 208,
    not_helpful_count: 26,
  },
  {
    id: "kba_005",
    title: "Coffee Machine Daily Maintenance Guide",
    slug: "coffee-machine-daily-maintenance",
    excerpt: "Step-by-step daily maintenance procedures for commercial coffee machines including cleaning, descaling, and troubleshooting common issues.",
    body_html: `<h2 id="overview">Overview</h2><p>Proper daily maintenance of coffee machines extends equipment life and ensures consistent beverage quality. Follow these procedures at the start and end of each day.</p><h2 id="daily-cleaning">Daily Cleaning Procedure</h2><h3 id="morning-prep">Morning Preparation</h3><ol><li>Flush the brew group with clean water (3 cycles)</li><li>Wipe steam wands with a damp cloth</li><li>Check water filters and replace if indicator shows</li><li>Verify milk system is clean and connected</li></ol><h3 id="end-of-day">End of Day Cleaning</h3><ol><li>Run cleaning tablet through the brew group</li><li>Soak portafilters in cleaning solution (15 minutes)</li><li>Empty and clean drip trays</li><li>Wipe all exterior surfaces</li><li>Empty coffee grounds container</li></ol><h2 id="weekly-descale">Weekly Descaling</h2><p>Descale the machine every Sunday using the approved descaling solution. Follow the machine manufacturer's instructions for the descaling cycle.</p><h2 id="troubleshooting">Troubleshooting</h2><p>Common issues and solutions:</p><ul><li><strong>Weak coffee:</strong> Check grind setting, clean brew group</li><li><strong>Machine not heating:</strong> Check power supply, verify thermostat</li><li><strong>Leaking steam wand:</strong> Replace O-ring, check valve seat</li></ul>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_002",
    collection_ids: ["kbcol_003"],
    tags: ["coffee", "maintenance", "equipment", "daily-cleaning"],
    author_id: "usr_004",
    last_edited_by: "usr_004",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "overview", text: "Overview", level: 2 },
      { id: "daily-cleaning", text: "Daily Cleaning Procedure", level: 2 },
      { id: "morning-prep", text: "Morning Preparation", level: 3 },
      { id: "end-of-day", text: "End of Day Cleaning", level: 3 },
      { id: "weekly-descale", text: "Weekly Descaling", level: 2 },
      { id: "troubleshooting", text: "Troubleshooting", level: 2 },
    ],
    created_at: "2026-02-08T10:00:00Z",
    updated_at: "2026-03-10T16:00:00Z",
    published_at: "2026-02-09T09:00:00Z",
    views_count: 156,
    helpful_count: 140,
    not_helpful_count: 12,
  },
  {
    id: "kba_006",
    title: "Allergen Management Policy",
    slug: "allergen-management-policy",
    excerpt: "Comprehensive allergen management policy covering identification, labeling, cross-contact prevention, and customer communication protocols.",
    body_html: `<h2 id="policy-overview">Policy Overview</h2><p>This policy establishes the framework for managing allergens across all food preparation and service areas. All staff must be trained on allergen identification and prevention measures.</p><h2 id="major-allergens">Major Allergens</h2><p>The following allergens must be declared and managed:</p><ul><li>Milk and dairy products</li><li>Eggs</li><li>Peanuts and tree nuts</li><li>Fish and shellfish</li><li>Wheat (gluten)</li><li>Soy</li><li>Sesame</li></ul><h2 id="prevention">Cross-Contact Prevention</h2><p>Use dedicated preparation areas and equipment for allergen-free orders. Always change gloves and wash hands between handling different allergens.</p><h2 id="communication">Customer Communication</h2><p>When a customer reports an allergy, the server must communicate directly with the kitchen manager. Use allergen alert tags on all orders with allergen requests.</p>`,
    status: "published",
    visibility: "public",
    category_id: "kbcat_001",
    collection_ids: ["kbcol_002"],
    tags: ["allergens", "food-safety", "policy", "compliance"],
    author_id: "usr_001",
    last_edited_by: "usr_001",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "policy-overview", text: "Policy Overview", level: 2 },
      { id: "major-allergens", text: "Major Allergens", level: 2 },
      { id: "prevention", text: "Cross-Contact Prevention", level: 2 },
      { id: "communication", text: "Customer Communication", level: 2 },
    ],
    created_at: "2026-02-10T10:00:00Z",
    updated_at: "2026-03-02T09:00:00Z",
    published_at: "2026-02-11T09:00:00Z",
    views_count: 201,
    helpful_count: 178,
    not_helpful_count: 18,
  },
  {
    id: "kba_007",
    title: "HVAC Preventive Maintenance Schedule",
    slug: "hvac-preventive-maintenance",
    excerpt: "Monthly and quarterly preventive maintenance procedures for HVAC systems including filter replacement, coil cleaning, and system inspections.",
    body_html: `<h2 id="schedule">Maintenance Schedule</h2><p>Regular preventive maintenance ensures efficient HVAC operation and extends equipment lifespan. Follow this schedule for all units.</p><h2 id="monthly">Monthly Tasks</h2><ul><li>Replace or clean air filters</li><li>Inspect belts for wear and tension</li><li>Check refrigerant levels</li><li>Clean condensate drain lines</li><li>Test thermostat calibration</li></ul><h2 id="quarterly">Quarterly Tasks</h2><ul><li>Clean evaporator and condenser coils</li><li>Inspect ductwork for leaks</li><li>Test all safety controls</li><li>Lubricate moving parts</li><li>Check electrical connections</li></ul>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_007",
    collection_ids: ["kbcol_003"],
    tags: ["hvac", "maintenance", "preventive", "schedule"],
    author_id: "usr_002",
    last_edited_by: "usr_002",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "schedule", text: "Maintenance Schedule", level: 2 },
      { id: "monthly", text: "Monthly Tasks", level: 2 },
      { id: "quarterly", text: "Quarterly Tasks", level: 2 },
    ],
    created_at: "2026-02-12T10:00:00Z",
    updated_at: "2026-03-01T14:00:00Z",
    published_at: "2026-02-13T09:00:00Z",
    views_count: 98,
    helpful_count: 89,
    not_helpful_count: 7,
  },
  {
    id: "kba_008",
    title: "Customer Complaint Resolution Procedure",
    slug: "customer-complaint-resolution",
    excerpt: "Step-by-step procedure for handling customer complaints including initial response, escalation paths, and follow-up requirements.",
    body_html: `<h2 id="overview">Overview</h2><p>Effective complaint resolution is critical to customer retention. This procedure ensures consistent, professional handling of all customer complaints.</p><h2 id="initial-response">Initial Response</h2><p>Acknowledge the complaint within 2 minutes. Listen actively, apologize sincerely, and assure the customer that you will resolve their concern.</p><h2 id="escalation">Escalation Paths</h2><p>If you cannot resolve the issue directly, escalate to the shift manager. For complaints involving safety or health concerns, escalate immediately to the location manager.</p><h2 id="follow-up">Follow-Up</h2><p>All complaints must be logged in the system within 1 hour. Follow up with the customer within 24 hours to confirm resolution.</p>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_006",
    collection_ids: [],
    tags: ["customer-service", "complaints", "resolution", "escalation"],
    author_id: "usr_004",
    last_edited_by: "usr_002",
    sop_source_id: "sop_002",
    sop_source_name: "Customer Complaint Resolution",
    featured_image: null,
    table_of_contents: [
      { id: "overview", text: "Overview", level: 2 },
      { id: "initial-response", text: "Initial Response", level: 2 },
      { id: "escalation", text: "Escalation Paths", level: 2 },
      { id: "follow-up", text: "Follow-Up", level: 2 },
    ],
    created_at: "2026-02-14T10:00:00Z",
    updated_at: "2026-03-06T11:00:00Z",
    published_at: "2026-02-15T09:00:00Z",
    views_count: 178,
    helpful_count: 156,
    not_helpful_count: 20,
  },
  {
    id: "kba_009",
    title: "Fire Safety & Emergency Evacuation Plan",
    slug: "fire-safety-emergency-evacuation",
    excerpt: "Emergency evacuation procedures, fire extinguisher locations, assembly points, and staff responsibilities during emergencies.",
    body_html: `<h2 id="purpose">Purpose</h2><p>This plan establishes procedures for responding to fire emergencies and evacuating all occupants safely.</p><h2 id="prevention">Fire Prevention</h2><p>Keep all exits clear, maintain fire extinguishers, and report any hazards immediately. Never block fire exits or remove fire safety equipment.</p><h2 id="evacuation">Evacuation Procedure</h2><ol><li>Activate the nearest fire alarm</li><li>Call emergency services (911)</li><li>Assist customers and colleagues to the nearest exit</li><li>Do not use elevators</li><li>Proceed to the designated assembly point</li><li>Account for all staff using the attendance roster</li></ol><h2 id="assembly-points">Assembly Points</h2><p>Each location has designated assembly points. Your manager will show you the locations during orientation.</p>`,
    status: "published",
    visibility: "public",
    category_id: "kbcat_005",
    collection_ids: ["kbcol_002"],
    tags: ["fire-safety", "emergency", "evacuation", "safety"],
    author_id: "usr_002",
    last_edited_by: "usr_002",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "purpose", text: "Purpose", level: 2 },
      { id: "prevention", text: "Fire Prevention", level: 2 },
      { id: "evacuation", text: "Evacuation Procedure", level: 2 },
      { id: "assembly-points", text: "Assembly Points", level: 2 },
    ],
    created_at: "2026-02-16T10:00:00Z",
    updated_at: "2026-03-04T09:00:00Z",
    published_at: "2026-02-17T09:00:00Z",
    views_count: 267,
    helpful_count: 245,
    not_helpful_count: 15,
  },
  {
    id: "kba_010",
    title: "Staff Uniform & Dress Code Policy",
    slug: "staff-uniform-dress-code",
    excerpt: "Comprehensive dress code policy including uniform requirements, personal grooming standards, and PPE requirements for each role.",
    body_html: `<h2 id="general">General Standards</h2><p>All staff must present a clean, professional appearance. Uniforms must be laundered and pressed before each shift.</p><h2 id="kitchen">Kitchen Staff Requirements</h2><ul><li>Chef coat (white or location-designated color)</li><li>Non-slip closed-toe shoes</li><li>Hair net or chef hat</li><li>Apron</li><li>No jewelry below the wrist</li></ul><h2 id="front-of-house">Front of House Requirements</h2><ul><li>Branded polo or button-down shirt</li><li>Dark pants or skirt (no jeans)</li><li>Closed-toe shoes</li><li>Name badge visible at all times</li></ul>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_004",
    collection_ids: ["kbcol_001"],
    tags: ["uniform", "dress-code", "policy", "grooming"],
    author_id: "usr_001",
    last_edited_by: "usr_001",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "general", text: "General Standards", level: 2 },
      { id: "kitchen", text: "Kitchen Staff Requirements", level: 2 },
      { id: "front-of-house", text: "Front of House Requirements", level: 2 },
    ],
    created_at: "2026-02-18T10:00:00Z",
    updated_at: "2026-02-28T09:00:00Z",
    published_at: "2026-02-19T09:00:00Z",
    views_count: 145,
    helpful_count: 128,
    not_helpful_count: 14,
  },
  {
    id: "kba_011",
    title: "Freezer Maintenance & Defrost Procedure",
    slug: "freezer-maintenance-defrost",
    excerpt: "Comprehensive guide to walk-in freezer maintenance including defrost cycles, ice buildup prevention, and corrective actions for temperature issues.",
    body_html: `<h2 id="overview">Overview</h2><p>Walk-in freezers require regular maintenance to operate efficiently. Ice buildup reduces cooling capacity and increases energy consumption.</p><h2 id="defrost-schedule">Defrost Schedule</h2><p>Automatic defrost cycles run every 8 hours. Manual defrost should be performed monthly or whenever ice buildup exceeds 5mm on the evaporator coils.</p><h2 id="maintenance-steps">Maintenance Steps</h2><ol><li>Check door gaskets for proper seal</li><li>Inspect floor drain for blockages</li><li>Verify fan motors are operating correctly</li><li>Clean condenser coils</li><li>Test temperature alarms</li></ol>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_003",
    collection_ids: ["kbcol_003"],
    tags: ["freezer", "maintenance", "defrost", "refrigeration"],
    author_id: "usr_002",
    last_edited_by: "usr_005",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "overview", text: "Overview", level: 2 },
      { id: "defrost-schedule", text: "Defrost Schedule", level: 2 },
      { id: "maintenance-steps", text: "Maintenance Steps", level: 2 },
    ],
    created_at: "2026-02-20T10:00:00Z",
    updated_at: "2026-03-09T14:00:00Z",
    published_at: "2026-02-21T09:00:00Z",
    views_count: 134,
    helpful_count: 121,
    not_helpful_count: 10,
  },
  {
    id: "kba_012",
    title: "Daily Opening Procedures",
    slug: "daily-opening-procedures",
    excerpt: "Step-by-step daily opening procedures for all locations covering equipment startup, safety checks, and preparation tasks.",
    body_html: `<h2 id="before-opening">Before Opening</h2><p>Arrive at least 30 minutes before scheduled opening time. Complete all safety checks and equipment startups before the first customer arrives.</p><h2 id="checklist">Opening Checklist</h2><ol><li>Disarm the security system</li><li>Turn on all lights and HVAC systems</li><li>Verify refrigeration temperatures</li><li>Check prep stations and restock as needed</li><li>Review the daily schedule and special events</li><li>Conduct a brief team huddle</li></ol>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_006",
    collection_ids: [],
    tags: ["opening", "daily", "operations", "checklist"],
    author_id: "usr_005",
    last_edited_by: "usr_005",
    sop_source_id: "sop_003",
    sop_source_name: "Daily Opening & Closing Checklist",
    featured_image: null,
    table_of_contents: [
      { id: "before-opening", text: "Before Opening", level: 2 },
      { id: "checklist", text: "Opening Checklist", level: 2 },
    ],
    created_at: "2026-02-22T10:00:00Z",
    updated_at: "2026-03-11T09:00:00Z",
    published_at: "2026-02-23T09:00:00Z",
    views_count: 189,
    helpful_count: 172,
    not_helpful_count: 14,
  },
  {
    id: "kba_013",
    title: "HACCP Plan Implementation Guide",
    slug: "haccp-plan-implementation",
    excerpt: "Detailed guide for implementing HACCP plans including hazard analysis, critical control points identification, and monitoring procedures.",
    body_html: `<h2 id="introduction">Introduction to HACCP</h2><p>HACCP (Hazard Analysis Critical Control Points) is a systematic approach to food safety that identifies and controls potential hazards in food production.</p><h2 id="seven-principles">The Seven HACCP Principles</h2><ol><li>Conduct a hazard analysis</li><li>Determine critical control points (CCPs)</li><li>Establish critical limits</li><li>Establish monitoring procedures</li><li>Establish corrective actions</li><li>Establish verification procedures</li><li>Establish record-keeping and documentation</li></ol>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_005",
    collection_ids: [],
    tags: ["haccp", "food-safety", "compliance", "critical-control"],
    author_id: "usr_003",
    last_edited_by: "usr_003",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "introduction", text: "Introduction to HACCP", level: 2 },
      { id: "seven-principles", text: "The Seven HACCP Principles", level: 2 },
    ],
    created_at: "2026-02-24T10:00:00Z",
    updated_at: "2026-03-06T09:00:00Z",
    published_at: "2026-02-25T09:00:00Z",
    views_count: 156,
    helpful_count: 143,
    not_helpful_count: 11,
  },
  {
    id: "kba_014",
    title: "Pest Control Prevention Measures",
    slug: "pest-control-prevention",
    excerpt: "Preventive pest control measures including sanitation standards, inspection schedules, and vendor coordination procedures.",
    body_html: `<h2 id="overview">Overview</h2><p>Effective pest control begins with prevention. Maintaining high sanitation standards significantly reduces pest activity.</p><h2 id="prevention-measures">Prevention Measures</h2><ul><li>Seal all entry points (gaps around pipes, doors, windows)</li><li>Keep food storage areas clean and organized</li><li>Remove trash and waste promptly</li><li>Store all food in sealed containers</li><li>Maintain proper drainage</li></ul><h2 id="inspection-schedule">Inspection Schedule</h2><p>Daily self-inspections by staff. Monthly professional inspections by the contracted pest control vendor. Immediate inspection if any pest activity is observed.</p>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_001",
    collection_ids: [],
    tags: ["pest-control", "sanitation", "prevention", "hygiene"],
    author_id: "usr_003",
    last_edited_by: "usr_003",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "overview", text: "Overview", level: 2 },
      { id: "prevention-measures", text: "Prevention Measures", level: 2 },
      { id: "inspection-schedule", text: "Inspection Schedule", level: 2 },
    ],
    created_at: "2026-02-26T10:00:00Z",
    updated_at: "2026-03-03T09:00:00Z",
    published_at: "2026-02-27T09:00:00Z",
    views_count: 112,
    helpful_count: 101,
    not_helpful_count: 9,
  },
  {
    id: "kba_015",
    title: "Barista Training Manual",
    slug: "barista-training-manual",
    excerpt: "Comprehensive training manual for baristas covering espresso extraction, milk texturing, latte art basics, and drink recipes.",
    body_html: `<h2 id="espresso-basics">Espresso Basics</h2><p>A proper espresso shot requires 18-20g of coffee, yielding 36-40g of liquid in 25-30 seconds. The grind, dose, and tamp must be consistent.</p><h2 id="milk-texturing">Milk Texturing</h2><p>Steam milk to 55-65&deg;C (131-149&deg;F). Position the steam wand just below the surface to create microfoam. The milk should have a glossy, paint-like appearance.</p><h2 id="drink-recipes">Standard Drink Recipes</h2><ul><li><strong>Cappuccino:</strong> Double espresso, equal parts steamed milk and foam</li><li><strong>Latte:</strong> Double espresso, steamed milk, thin layer of foam</li><li><strong>Flat White:</strong> Double ristretto, microfoam milk, no dry foam</li></ul>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_004",
    collection_ids: ["kbcol_001"],
    tags: ["barista", "coffee", "training", "espresso"],
    author_id: "usr_004",
    last_edited_by: "usr_004",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "espresso-basics", text: "Espresso Basics", level: 2 },
      { id: "milk-texturing", text: "Milk Texturing", level: 2 },
      { id: "drink-recipes", text: "Standard Drink Recipes", level: 2 },
    ],
    created_at: "2026-02-28T10:00:00Z",
    updated_at: "2026-03-07T09:00:00Z",
    published_at: "2026-03-01T09:00:00Z",
    views_count: 189,
    helpful_count: 175,
    not_helpful_count: 11,
  },
  {
    id: "kba_016",
    title: "Dishwasher Machine Operation & Maintenance",
    slug: "dishwasher-operation-maintenance",
    excerpt: "Operating procedures and maintenance schedule for commercial dishwashers including chemical dosing, water temperature requirements, and cleaning cycles.",
    body_html: `<h2 id="operation">Operating Procedure</h2><p>Ensure water temperature reaches 60&deg;C for wash and 82&deg;C for rinse. Load racks properly without overloading for effective cleaning.</p><h2 id="maintenance">Daily Maintenance</h2><ul><li>Clean interior surfaces at end of shift</li><li>Remove and clean filters</li><li>Check chemical levels and refill as needed</li><li>Inspect spray arms for blockages</li></ul>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_002",
    collection_ids: ["kbcol_003"],
    tags: ["dishwasher", "equipment", "maintenance", "cleaning"],
    author_id: "usr_005",
    last_edited_by: "usr_005",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "operation", text: "Operating Procedure", level: 2 },
      { id: "maintenance", text: "Daily Maintenance", level: 2 },
    ],
    created_at: "2026-03-01T10:00:00Z",
    updated_at: "2026-03-08T09:00:00Z",
    published_at: "2026-03-02T09:00:00Z",
    views_count: 87,
    helpful_count: 79,
    not_helpful_count: 6,
  },
  {
    id: "kba_017",
    title: "Food Storage Temperature Guidelines",
    slug: "food-storage-temperature-guidelines",
    excerpt: "Complete temperature guidelines for storing various food categories including fresh produce, dairy, meats, and prepared foods.",
    body_html: `<h2 id="guidelines">Storage Guidelines</h2><p>Proper food storage is essential for safety and quality. Each food category has specific temperature and placement requirements.</p><h2 id="categories">Storage by Category</h2><ul><li><strong>Fresh meats:</strong> 0-2&deg;C, bottom shelf</li><li><strong>Dairy:</strong> 2-4&deg;C, middle shelf</li><li><strong>Fruits & vegetables:</strong> 4-7&deg;C, designated crisper</li><li><strong>Prepared foods:</strong> 0-4&deg;C, top shelf, covered and labeled</li></ul><h2 id="fifo">FIFO Principle</h2><p>Always follow First In, First Out. New stock goes behind existing stock. Check dates daily and discard expired items.</p>`,
    status: "published",
    visibility: "public",
    category_id: "kbcat_008",
    collection_ids: [],
    tags: ["food-storage", "temperature", "guidelines", "fifo"],
    author_id: "usr_001",
    last_edited_by: "usr_003",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "guidelines", text: "Storage Guidelines", level: 2 },
      { id: "categories", text: "Storage by Category", level: 2 },
      { id: "fifo", text: "FIFO Principle", level: 2 },
    ],
    created_at: "2026-03-02T10:00:00Z",
    updated_at: "2026-03-09T09:00:00Z",
    published_at: "2026-03-03T09:00:00Z",
    views_count: 145,
    helpful_count: 132,
    not_helpful_count: 10,
  },
  {
    id: "kba_018",
    title: "Health Inspection Preparation Checklist",
    slug: "health-inspection-preparation",
    excerpt: "Pre-inspection checklist covering all areas that health inspectors typically evaluate, with tips for maintaining inspection readiness.",
    body_html: `<h2 id="preparation">Preparation Checklist</h2><p>Health inspections can occur without advance notice. Maintain inspection readiness at all times by following these daily standards.</p><h2 id="key-areas">Key Inspection Areas</h2><ul><li>Food storage and temperature logs</li><li>Hand washing stations (stocked and accessible)</li><li>Pest control documentation</li><li>Staff certifications and training records</li><li>Cleaning schedules and logs</li><li>Equipment maintenance records</li></ul>`,
    status: "published",
    visibility: "internal",
    category_id: "kbcat_005",
    collection_ids: [],
    tags: ["health-inspection", "compliance", "checklist", "preparation"],
    author_id: "usr_003",
    last_edited_by: "usr_003",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "preparation", text: "Preparation Checklist", level: 2 },
      { id: "key-areas", text: "Key Inspection Areas", level: 2 },
    ],
    created_at: "2026-03-03T10:00:00Z",
    updated_at: "2026-03-10T09:00:00Z",
    published_at: "2026-03-04T09:00:00Z",
    views_count: 198,
    helpful_count: 182,
    not_helpful_count: 13,
  },
  // Draft articles
  {
    id: "kba_019",
    title: "Sustainability Practices Guide",
    slug: "sustainability-practices",
    excerpt: "Guide to implementing sustainable practices including waste reduction, energy conservation, and eco-friendly procurement policies.",
    body_html: `<h2 id="intro">Introduction</h2><p>Our commitment to sustainability drives operational improvements and reduces environmental impact. This guide outlines practical steps for every team member.</p><h2 id="waste-reduction">Waste Reduction</h2><p>Implement portion control, composting programs, and recycling stations. Track waste metrics weekly.</p>`,
    status: "draft",
    visibility: "internal",
    category_id: "kbcat_006",
    collection_ids: [],
    tags: ["sustainability", "waste-reduction", "eco-friendly"],
    author_id: "usr_001",
    last_edited_by: "usr_001",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "intro", text: "Introduction", level: 2 },
      { id: "waste-reduction", text: "Waste Reduction", level: 2 },
    ],
    created_at: "2026-03-05T10:00:00Z",
    updated_at: "2026-03-12T09:00:00Z",
    published_at: null,
    views_count: 0,
    helpful_count: 0,
    not_helpful_count: 0,
  },
  {
    id: "kba_020",
    title: "First Aid Response Procedures",
    slug: "first-aid-response",
    excerpt: "Emergency first aid procedures for common workplace injuries including burns, cuts, slips and falls.",
    body_html: `<h2 id="overview">Overview</h2><p>All staff should be familiar with basic first aid procedures. First aid kits are located in each department. Report all incidents immediately.</p>`,
    status: "draft",
    visibility: "internal",
    category_id: "kbcat_005",
    collection_ids: [],
    tags: ["first-aid", "emergency", "safety", "injuries"],
    author_id: "usr_002",
    last_edited_by: "usr_002",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "overview", text: "Overview", level: 2 },
    ],
    created_at: "2026-03-06T10:00:00Z",
    updated_at: "2026-03-11T09:00:00Z",
    published_at: null,
    views_count: 0,
    helpful_count: 0,
    not_helpful_count: 0,
  },
  {
    id: "kba_021",
    title: "Inventory Management Best Practices",
    slug: "inventory-management-best-practices",
    excerpt: "Best practices for managing food and supply inventory including ordering schedules, par levels, and waste tracking.",
    body_html: `<h2 id="par-levels">Setting Par Levels</h2><p>Par levels should be set based on average daily usage plus a 20% buffer. Review and adjust par levels monthly based on sales trends.</p>`,
    status: "draft",
    visibility: "internal",
    category_id: "kbcat_006",
    collection_ids: [],
    tags: ["inventory", "ordering", "par-levels", "management"],
    author_id: "usr_002",
    last_edited_by: "usr_002",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "par-levels", text: "Setting Par Levels", level: 2 },
    ],
    created_at: "2026-03-07T10:00:00Z",
    updated_at: "2026-03-13T09:00:00Z",
    published_at: null,
    views_count: 0,
    helpful_count: 0,
    not_helpful_count: 0,
  },
  {
    id: "kba_022",
    title: "Grease Trap Cleaning Procedure",
    slug: "grease-trap-cleaning",
    excerpt: "Detailed instructions for cleaning and maintaining grease traps, including frequency requirements and disposal procedures.",
    body_html: `<h2 id="procedure">Cleaning Procedure</h2><p>Grease traps must be cleaned weekly or when filled to 25% capacity. Use approved cleaning supplies and dispose of grease through the contracted waste hauler.</p>`,
    status: "draft",
    visibility: "internal",
    category_id: "kbcat_002",
    collection_ids: [],
    tags: ["grease-trap", "cleaning", "maintenance"],
    author_id: "usr_005",
    last_edited_by: "usr_005",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "procedure", text: "Cleaning Procedure", level: 2 },
    ],
    created_at: "2026-03-08T10:00:00Z",
    updated_at: "2026-03-12T09:00:00Z",
    published_at: null,
    views_count: 0,
    helpful_count: 0,
    not_helpful_count: 0,
  },
  {
    id: "kba_023",
    title: "Walk-In Cooler Organization Standards",
    slug: "walk-in-cooler-organization",
    excerpt: "Standards for organizing walk-in cooler storage including shelf assignments, labeling requirements, and rotation procedures.",
    body_html: `<h2 id="organization">Organization Standards</h2><p>A well-organized cooler improves efficiency and food safety. All items must be labeled with product name and date.</p><h2 id="shelf-assignments">Shelf Assignments</h2><ul><li>Top shelf: Ready-to-eat foods and dairy</li><li>Middle shelf: Produce and prepared items</li><li>Bottom shelf: Raw meats (in drip-proof containers)</li></ul>`,
    status: "draft",
    visibility: "internal",
    category_id: "kbcat_008",
    collection_ids: [],
    tags: ["cooler", "organization", "storage", "labeling"],
    author_id: "usr_003",
    last_edited_by: "usr_003",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "organization", text: "Organization Standards", level: 2 },
      { id: "shelf-assignments", text: "Shelf Assignments", level: 2 },
    ],
    created_at: "2026-03-09T10:00:00Z",
    updated_at: "2026-03-13T09:00:00Z",
    published_at: null,
    views_count: 0,
    helpful_count: 0,
    not_helpful_count: 0,
  },
  // Archived articles
  {
    id: "kba_024",
    title: "Legacy POS System Quick Reference (Deprecated)",
    slug: "legacy-pos-system-reference",
    excerpt: "Quick reference guide for the legacy POS system. This article is archived as we have migrated to the new POS platform.",
    body_html: `<h2 id="notice">Deprecation Notice</h2><p>This article refers to our legacy POS system which has been replaced. Please refer to the new POS Training Guide for current procedures.</p>`,
    status: "archived",
    visibility: "internal",
    category_id: "kbcat_004",
    collection_ids: [],
    tags: ["pos", "legacy", "deprecated"],
    author_id: "usr_004",
    last_edited_by: "usr_001",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "notice", text: "Deprecation Notice", level: 2 },
    ],
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-03-01T09:00:00Z",
    published_at: "2026-01-11T09:00:00Z",
    views_count: 45,
    helpful_count: 12,
    not_helpful_count: 30,
  },
  {
    id: "kba_025",
    title: "Old Supplier Contact List (Archived)",
    slug: "old-supplier-contact-list",
    excerpt: "Previous supplier contact information. Archived — see updated supplier directory in the Operations section.",
    body_html: `<h2 id="archived">Archived Content</h2><p>This supplier list is no longer current. Please refer to the updated supplier directory maintained by the procurement team.</p>`,
    status: "archived",
    visibility: "internal",
    category_id: "kbcat_006",
    collection_ids: [],
    tags: ["suppliers", "contacts", "archived"],
    author_id: "usr_002",
    last_edited_by: "usr_002",
    sop_source_id: null,
    sop_source_name: null,
    featured_image: null,
    table_of_contents: [
      { id: "archived", text: "Archived Content", level: 2 },
    ],
    created_at: "2026-01-05T10:00:00Z",
    updated_at: "2026-02-15T09:00:00Z",
    published_at: "2026-01-06T09:00:00Z",
    views_count: 23,
    helpful_count: 5,
    not_helpful_count: 15,
  },
];

// ---------- Analytics (6 months for top 10 articles) ----------

const topArticleIds = [
  "kba_001", "kba_002", "kba_003", "kba_004", "kba_005",
  "kba_006", "kba_008", "kba_009", "kba_012", "kba_015",
];

const periods = ["2025-10", "2025-11", "2025-12", "2026-01", "2026-02", "2026-03"];

function generateAnalytics(articleId: string, periodIdx: number): ArticleAnalytics {
  const baseViews = 30 + (topArticleIds.indexOf(articleId) === 0 ? 50 : topArticleIds.indexOf(articleId) * 5);
  const growth = 1 + periodIdx * 0.15;
  const views = Math.round(baseViews * growth);
  const uniqueViews = Math.round(views * 0.7);
  const helpfulVotes = Math.round(views * 0.25);
  const notHelpfulVotes = Math.round(views * 0.03);
  const avgReadTime = 120 + Math.round(Math.random() * 180);

  return {
    article_id: articleId,
    period: periods[periodIdx],
    views,
    unique_views: uniqueViews,
    helpful_votes: helpfulVotes,
    not_helpful_votes: notHelpfulVotes,
    avg_read_time_seconds: avgReadTime,
    referral_source: [
      { source: "search", count: Math.round(views * 0.45) },
      { source: "direct", count: Math.round(views * 0.25) },
      { source: "ticket_sidebar", count: Math.round(views * 0.18) },
      { source: "sop_link", count: Math.round(views * 0.08) },
      { source: "external", count: Math.round(views * 0.04) },
    ],
  };
}

export const kbAnalytics: ArticleAnalytics[] = topArticleIds.flatMap((id) =>
  periods.map((_, idx) => generateAnalytics(id, idx))
);

// ---------- 12 Search Gaps ----------

export const kbSearchGaps: KBSearchGap[] = [
  { id: "kbsg_001", query: "allergen policy", search_count: 23, last_searched_at: "2026-03-14T10:00:00Z", has_results: true, result_count: 1 },
  { id: "kbsg_002", query: "fire drill procedure", search_count: 18, last_searched_at: "2026-03-13T14:00:00Z", has_results: false, result_count: 0 },
  { id: "kbsg_003", query: "wifi password", search_count: 15, last_searched_at: "2026-03-14T09:00:00Z", has_results: false, result_count: 0 },
  { id: "kbsg_004", query: "uniform policy", search_count: 12, last_searched_at: "2026-03-14T07:00:00Z", has_results: true, result_count: 1 },
  { id: "kbsg_005", query: "sick leave policy", search_count: 11, last_searched_at: "2026-03-13T16:00:00Z", has_results: false, result_count: 0 },
  { id: "kbsg_006", query: "overtime approval", search_count: 9, last_searched_at: "2026-03-12T11:00:00Z", has_results: false, result_count: 0 },
  { id: "kbsg_007", query: "delivery schedule", search_count: 8, last_searched_at: "2026-03-13T08:00:00Z", has_results: false, result_count: 0 },
  { id: "kbsg_008", query: "food safety certification", search_count: 7, last_searched_at: "2026-03-12T15:00:00Z", has_results: true, result_count: 2 },
  { id: "kbsg_009", query: "break room rules", search_count: 6, last_searched_at: "2026-03-11T10:00:00Z", has_results: false, result_count: 0 },
  { id: "kbsg_010", query: "parking policy", search_count: 5, last_searched_at: "2026-03-10T09:00:00Z", has_results: false, result_count: 0 },
  { id: "kbsg_011", query: "payroll schedule", search_count: 4, last_searched_at: "2026-03-09T14:00:00Z", has_results: false, result_count: 0 },
  { id: "kbsg_012", query: "equipment warranty", search_count: 3, last_searched_at: "2026-03-08T11:00:00Z", has_results: true, result_count: 1 },
];

export const kbSimilarArticles = [
  { id: "kb_002", title: "Equipment Maintenance Checklist", relevance: 0.92 },
  { id: "kb_005", title: "Daily Opening Procedures", relevance: 0.85 },
  { id: "kb_008", title: "Health & Safety Guidelines", relevance: 0.78 },
];

export const kbSuggestedTags = ["maintenance", "equipment", "daily-cleaning", "barista", "operations"];

export const kbReadability = {
  score: 72,
  level: "Good",
  avgSentenceLength: 14,
  complexWordPct: 8,
};
